/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "referee_2_est.v:2" *)
module referee_2_est(push_0, push_1, push_2, push_3, pop, data_in, almost_full_0, almost_full_1, almost_full_2, almost_full_3, empty, clk, state);
  (* src = "referee_2_est.v:17" *)
  wire _000_;
  (* src = "referee_2_est.v:17" *)
  wire _001_;
  (* src = "referee_2_est.v:17" *)
  wire _002_;
  (* src = "referee_2_est.v:17" *)
  wire _003_;
  (* src = "referee_2_est.v:17" *)
  wire _004_;
  (* src = "referee_2_est.v:17" *)
  wire _005_;
  (* src = "referee_2_est.v:17" *)
  wire _006_;
  (* src = "referee_2_est.v:17" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  (* src = "referee_2_est.v:7" *)
  input almost_full_0;
  (* src = "referee_2_est.v:7" *)
  input almost_full_1;
  (* src = "referee_2_est.v:7" *)
  input almost_full_2;
  (* src = "referee_2_est.v:7" *)
  input almost_full_3;
  (* src = "referee_2_est.v:9" *)
  input clk;
  (* src = "referee_2_est.v:12" *)
  wire [1:0] cont;
  (* src = "referee_2_est.v:6" *)
  input [11:0] data_in;
  (* src = "referee_2_est.v:8" *)
  input empty;
  (* src = "referee_2_est.v:4" *)
  output pop;
  (* src = "referee_2_est.v:13" *)
  wire pop_toggle;
  (* src = "referee_2_est.v:3" *)
  output push_0;
  (* src = "referee_2_est.v:3" *)
  output push_1;
  (* src = "referee_2_est.v:3" *)
  output push_2;
  (* src = "referee_2_est.v:3" *)
  output push_3;
  (* src = "referee_2_est.v:15" *)
  wire push_enable;
  (* src = "referee_2_est.v:14" *)
  wire push_toggle;
  (* src = "referee_2_est.v:10" *)
  input [3:0] state;
  NOT _054_ (
    .A(state[0]),
    .Y(_008_)
  );
  NOT _055_ (
    .A(data_in[11]),
    .Y(_009_)
  );
  NOT _056_ (
    .A(data_in[10]),
    .Y(_010_)
  );
  NOT _057_ (
    .A(push_enable),
    .Y(_011_)
  );
  NOT _058_ (
    .A(pop_toggle),
    .Y(_012_)
  );
  NOR _059_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_013_)
  );
  NAND _060_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_014_)
  );
  NOR _061_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_015_)
  );
  NOT _062_ (
    .A(_015_),
    .Y(_016_)
  );
  NAND _063_ (
    .A(_014_),
    .B(_015_),
    .Y(_017_)
  );
  NOR _064_ (
    .A(_013_),
    .B(_016_),
    .Y(_018_)
  );
  NOR _065_ (
    .A(_013_),
    .B(_017_),
    .Y(_019_)
  );
  NAND _066_ (
    .A(_014_),
    .B(_018_),
    .Y(_020_)
  );
  NOR _067_ (
    .A(_012_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _068_ (
    .A(pop_toggle),
    .B(_019_),
    .Y(_022_)
  );
  NOR _069_ (
    .A(push_enable),
    .B(_021_),
    .Y(_023_)
  );
  NOR _070_ (
    .A(state[1]),
    .B(_008_),
    .Y(_024_)
  );
  NAND _071_ (
    .A(state[0]),
    .B(_013_),
    .Y(_025_)
  );
  NOR _072_ (
    .A(state[1]),
    .B(_025_),
    .Y(_026_)
  );
  NAND _073_ (
    .A(_013_),
    .B(_024_),
    .Y(_027_)
  );
  NAND _074_ (
    .A(empty),
    .B(_019_),
    .Y(_028_)
  );
  NAND _075_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _076_ (
    .A(_023_),
    .B(_029_),
    .Y(_006_)
  );
  NOR _077_ (
    .A(empty),
    .B(_020_),
    .Y(_030_)
  );
  NOR _078_ (
    .A(empty),
    .B(_022_),
    .Y(_031_)
  );
  NAND _079_ (
    .A(push_toggle),
    .B(_031_),
    .Y(_032_)
  );
  NOT _080_ (
    .A(_032_),
    .Y(_033_)
  );
  NOR _081_ (
    .A(push_toggle),
    .B(_031_),
    .Y(_034_)
  );
  NAND _082_ (
    .A(_027_),
    .B(_032_),
    .Y(_035_)
  );
  NOR _083_ (
    .A(_034_),
    .B(_035_),
    .Y(_007_)
  );
  NOR _084_ (
    .A(pop_toggle),
    .B(_030_),
    .Y(_036_)
  );
  NOR _085_ (
    .A(_026_),
    .B(_036_),
    .Y(_037_)
  );
  NOT _086_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _087_ (
    .A(_031_),
    .B(_038_),
    .Y(_001_)
  );
  NOR _088_ (
    .A(_011_),
    .B(_032_),
    .Y(_039_)
  );
  NAND _089_ (
    .A(push_enable),
    .B(_033_),
    .Y(_040_)
  );
  NAND _090_ (
    .A(data_in[10]),
    .B(_039_),
    .Y(_041_)
  );
  NOR _091_ (
    .A(_009_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _092_ (
    .A(push_3),
    .B(_042_),
    .Y(_043_)
  );
  NOR _093_ (
    .A(_026_),
    .B(_043_),
    .Y(_005_)
  );
  NAND _094_ (
    .A(data_in[11]),
    .B(_010_),
    .Y(_044_)
  );
  NOR _095_ (
    .A(_040_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _096_ (
    .A(push_2),
    .B(_045_),
    .Y(_046_)
  );
  NOR _097_ (
    .A(_026_),
    .B(_046_),
    .Y(_004_)
  );
  NOR _098_ (
    .A(data_in[11]),
    .B(_041_),
    .Y(_047_)
  );
  NOR _099_ (
    .A(push_1),
    .B(_047_),
    .Y(_048_)
  );
  NOR _100_ (
    .A(_026_),
    .B(_048_),
    .Y(_003_)
  );
  NOR _101_ (
    .A(pop),
    .B(_021_),
    .Y(_049_)
  );
  NOR _102_ (
    .A(_029_),
    .B(_049_),
    .Y(_000_)
  );
  NOR _103_ (
    .A(data_in[11]),
    .B(data_in[10]),
    .Y(_050_)
  );
  NOT _104_ (
    .A(_050_),
    .Y(_051_)
  );
  NOR _105_ (
    .A(_040_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _106_ (
    .A(push_0),
    .B(_052_),
    .Y(_053_)
  );
  NOR _107_ (
    .A(_026_),
    .B(_053_),
    .Y(_002_)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _108_ (
    .C(clk),
    .D(_002_),
    .Q(push_0)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _109_ (
    .C(clk),
    .D(_000_),
    .Q(pop)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _110_ (
    .C(clk),
    .D(_003_),
    .Q(push_1)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _111_ (
    .C(clk),
    .D(_004_),
    .Q(push_2)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _112_ (
    .C(clk),
    .D(_005_),
    .Q(push_3)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _113_ (
    .C(clk),
    .D(_001_),
    .Q(pop_toggle)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _114_ (
    .C(clk),
    .D(_007_),
    .Q(push_toggle)
  );
  (* src = "referee_2_est.v:17" *)
  DFF _115_ (
    .C(clk),
    .D(_006_),
    .Q(push_enable)
  );
  assign cont = 2'h0;
endmodule
