/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "referee_2_est.v:2" *)
module referee_2_est(push_0, push_1, push_2, push_3, pop, almost_full_0, almost_full_1, almost_full_2, almost_full_3, empty, clk, reset);
  (* src = "referee_2_est.v:14" *)
  wire [1:0] _000_;
  (* src = "referee_2_est.v:14" *)
  wire _001_;
  (* src = "referee_2_est.v:14" *)
  wire _002_;
  (* src = "referee_2_est.v:14" *)
  wire _003_;
  (* src = "referee_2_est.v:14" *)
  wire _004_;
  (* src = "referee_2_est.v:14" *)
  wire _005_;
  (* src = "referee_2_est.v:14" *)
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* src = "referee_2_est.v:7" *)
  input almost_full_0;
  (* src = "referee_2_est.v:7" *)
  input almost_full_1;
  (* src = "referee_2_est.v:7" *)
  input almost_full_2;
  (* src = "referee_2_est.v:7" *)
  input almost_full_3;
  (* src = "referee_2_est.v:9" *)
  input clk;
  (* src = "referee_2_est.v:11" *)
  wire [1:0] cont;
  (* src = "referee_2_est.v:8" *)
  input empty;
  (* src = "referee_2_est.v:4" *)
  output pop;
  (* src = "referee_2_est.v:12" *)
  wire pop_toggle;
  (* src = "referee_2_est.v:3" *)
  output push_0;
  (* src = "referee_2_est.v:3" *)
  output push_1;
  (* src = "referee_2_est.v:3" *)
  output push_2;
  (* src = "referee_2_est.v:3" *)
  output push_3;
  (* src = "referee_2_est.v:9" *)
  input reset;
  NOT _046_ (
    .A(cont[0]),
    .Y(_007_)
  );
  NOT _047_ (
    .A(cont[1]),
    .Y(_008_)
  );
  NOT _048_ (
    .A(empty),
    .Y(_009_)
  );
  NOT _049_ (
    .A(reset),
    .Y(_010_)
  );
  NOT _050_ (
    .A(push_3),
    .Y(_011_)
  );
  NOT _051_ (
    .A(push_2),
    .Y(_012_)
  );
  NOT _052_ (
    .A(push_1),
    .Y(_013_)
  );
  NOR _053_ (
    .A(almost_full_0),
    .B(almost_full_1),
    .Y(_014_)
  );
  NOT _054_ (
    .A(_014_),
    .Y(_015_)
  );
  NOR _055_ (
    .A(almost_full_2),
    .B(almost_full_3),
    .Y(_016_)
  );
  NOT _056_ (
    .A(_016_),
    .Y(_017_)
  );
  NOR _057_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _058_ (
    .A(_009_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _059_ (
    .A(pop_toggle),
    .B(_019_),
    .Y(_020_)
  );
  NOR _060_ (
    .A(pop_toggle),
    .B(_019_),
    .Y(_021_)
  );
  NOR _061_ (
    .A(_010_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _062_ (
    .A(_020_),
    .B(_022_),
    .Y(_002_)
  );
  NAND _063_ (
    .A(cont[0]),
    .B(_018_),
    .Y(_023_)
  );
  NOT _064_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _065_ (
    .A(cont[0]),
    .B(_018_),
    .Y(_025_)
  );
  NOT _066_ (
    .A(_025_),
    .Y(_026_)
  );
  NAND _067_ (
    .A(reset),
    .B(_026_),
    .Y(_027_)
  );
  NOR _068_ (
    .A(_024_),
    .B(_027_),
    .Y(_000_[0])
  );
  NOR _069_ (
    .A(_008_),
    .B(_023_),
    .Y(_028_)
  );
  NAND _070_ (
    .A(_008_),
    .B(_023_),
    .Y(_029_)
  );
  NAND _071_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _072_ (
    .A(_028_),
    .B(_030_),
    .Y(_000_[1])
  );
  NAND _073_ (
    .A(reset),
    .B(_018_),
    .Y(_031_)
  );
  NOR _074_ (
    .A(_007_),
    .B(_008_),
    .Y(_032_)
  );
  NOR _075_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_033_)
  );
  NOR _076_ (
    .A(_011_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _077_ (
    .A(_032_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _078_ (
    .A(_031_),
    .B(_035_),
    .Y(_006_)
  );
  NOR _079_ (
    .A(cont[0]),
    .B(_008_),
    .Y(_036_)
  );
  NOR _080_ (
    .A(cont[1]),
    .B(_012_),
    .Y(_037_)
  );
  NOR _081_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _082_ (
    .A(_031_),
    .B(_038_),
    .Y(_005_)
  );
  NOR _083_ (
    .A(_007_),
    .B(cont[1]),
    .Y(_039_)
  );
  NOR _084_ (
    .A(_013_),
    .B(_036_),
    .Y(_040_)
  );
  NOR _085_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _086_ (
    .A(_031_),
    .B(_041_),
    .Y(_004_)
  );
  NAND _087_ (
    .A(pop_toggle),
    .B(reset),
    .Y(_042_)
  );
  NOR _088_ (
    .A(empty),
    .B(_042_),
    .Y(_001_)
  );
  NAND _089_ (
    .A(cont[1]),
    .B(push_0),
    .Y(_043_)
  );
  NOT _090_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _091_ (
    .A(_033_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _092_ (
    .A(_031_),
    .B(_045_),
    .Y(_003_)
  );
  (* src = "referee_2_est.v:14" *)
  DFF _093_ (
    .C(clk),
    .D(_003_),
    .Q(push_0)
  );
  (* src = "referee_2_est.v:14" *)
  DFF _094_ (
    .C(clk),
    .D(_001_),
    .Q(pop)
  );
  (* src = "referee_2_est.v:14" *)
  DFF _095_ (
    .C(clk),
    .D(_004_),
    .Q(push_1)
  );
  (* src = "referee_2_est.v:14" *)
  DFF _096_ (
    .C(clk),
    .D(_005_),
    .Q(push_2)
  );
  (* src = "referee_2_est.v:14" *)
  DFF _097_ (
    .C(clk),
    .D(_006_),
    .Q(push_3)
  );
  (* src = "referee_2_est.v:14" *)
  DFF _098_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cont[0])
  );
  (* src = "referee_2_est.v:14" *)
  DFF _099_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cont[1])
  );
  (* src = "referee_2_est.v:14" *)
  DFF _100_ (
    .C(clk),
    .D(_002_),
    .Q(pop_toggle)
  );
endmodule
