/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "referee_2_est.v:2" *)
module referee_2_est(push_0, push_1, push_2, push_3, pop, almost_full_0, almost_full_1, almost_full_2, almost_full_3, empty, clk, reset);
  (* src = "referee_2_est.v:13" *)
  wire [1:0] _00_;
  (* src = "referee_2_est.v:13" *)
  wire _01_;
  (* src = "referee_2_est.v:13" *)
  wire _02_;
  (* src = "referee_2_est.v:13" *)
  wire _03_;
  (* src = "referee_2_est.v:13" *)
  wire _04_;
  (* src = "referee_2_est.v:13" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "referee_2_est.v:7" *)
  input almost_full_0;
  (* src = "referee_2_est.v:7" *)
  input almost_full_1;
  (* src = "referee_2_est.v:7" *)
  input almost_full_2;
  (* src = "referee_2_est.v:7" *)
  input almost_full_3;
  (* src = "referee_2_est.v:9" *)
  input clk;
  (* src = "referee_2_est.v:11" *)
  wire [1:0] cont;
  (* src = "referee_2_est.v:8" *)
  input empty;
  (* src = "referee_2_est.v:4" *)
  output pop;
  (* src = "referee_2_est.v:3" *)
  output push_0;
  (* src = "referee_2_est.v:3" *)
  output push_1;
  (* src = "referee_2_est.v:3" *)
  output push_2;
  (* src = "referee_2_est.v:3" *)
  output push_3;
  (* src = "referee_2_est.v:9" *)
  input reset;
  NOT _39_ (
    .A(cont[0]),
    .Y(_06_)
  );
  NOT _40_ (
    .A(cont[1]),
    .Y(_07_)
  );
  NOT _41_ (
    .A(reset),
    .Y(_08_)
  );
  NOT _42_ (
    .A(push_3),
    .Y(_09_)
  );
  NOT _43_ (
    .A(push_2),
    .Y(_10_)
  );
  NOT _44_ (
    .A(push_1),
    .Y(_11_)
  );
  NOR _45_ (
    .A(almost_full_0),
    .B(almost_full_1),
    .Y(_12_)
  );
  NOT _46_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _47_ (
    .A(almost_full_2),
    .B(almost_full_3),
    .Y(_14_)
  );
  NOT _48_ (
    .A(_14_),
    .Y(_15_)
  );
  NOR _49_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  NAND _50_ (
    .A(cont[0]),
    .B(_16_),
    .Y(_17_)
  );
  NOT _51_ (
    .A(_17_),
    .Y(_18_)
  );
  NOR _52_ (
    .A(cont[0]),
    .B(_16_),
    .Y(_19_)
  );
  NOT _53_ (
    .A(_19_),
    .Y(_20_)
  );
  NAND _54_ (
    .A(reset),
    .B(_20_),
    .Y(_21_)
  );
  NOR _55_ (
    .A(_18_),
    .B(_21_),
    .Y(_00_[0])
  );
  NOR _56_ (
    .A(_07_),
    .B(_17_),
    .Y(_22_)
  );
  NAND _57_ (
    .A(_07_),
    .B(_17_),
    .Y(_23_)
  );
  NAND _58_ (
    .A(reset),
    .B(_23_),
    .Y(_24_)
  );
  NOR _59_ (
    .A(_22_),
    .B(_24_),
    .Y(_00_[1])
  );
  NAND _60_ (
    .A(reset),
    .B(_16_),
    .Y(_25_)
  );
  NOR _61_ (
    .A(_06_),
    .B(_07_),
    .Y(_26_)
  );
  NOR _62_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_27_)
  );
  NOR _63_ (
    .A(_09_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _64_ (
    .A(_26_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _65_ (
    .A(_25_),
    .B(_29_),
    .Y(_05_)
  );
  NOR _66_ (
    .A(cont[0]),
    .B(_07_),
    .Y(_30_)
  );
  NOR _67_ (
    .A(cont[1]),
    .B(_10_),
    .Y(_31_)
  );
  NOR _68_ (
    .A(_30_),
    .B(_31_),
    .Y(_32_)
  );
  NOR _69_ (
    .A(_25_),
    .B(_32_),
    .Y(_04_)
  );
  NOR _70_ (
    .A(_06_),
    .B(cont[1]),
    .Y(_33_)
  );
  NOR _71_ (
    .A(_11_),
    .B(_30_),
    .Y(_34_)
  );
  NOR _72_ (
    .A(_33_),
    .B(_34_),
    .Y(_35_)
  );
  NOR _73_ (
    .A(_25_),
    .B(_35_),
    .Y(_03_)
  );
  NOR _74_ (
    .A(_08_),
    .B(empty),
    .Y(_01_)
  );
  NAND _75_ (
    .A(cont[1]),
    .B(push_0),
    .Y(_36_)
  );
  NOT _76_ (
    .A(_36_),
    .Y(_37_)
  );
  NOR _77_ (
    .A(_27_),
    .B(_37_),
    .Y(_38_)
  );
  NOR _78_ (
    .A(_25_),
    .B(_38_),
    .Y(_02_)
  );
  (* src = "referee_2_est.v:13" *)
  DFF _79_ (
    .C(clk),
    .D(_02_),
    .Q(push_0)
  );
  (* src = "referee_2_est.v:13" *)
  DFF _80_ (
    .C(clk),
    .D(_01_),
    .Q(pop)
  );
  (* src = "referee_2_est.v:13" *)
  DFF _81_ (
    .C(clk),
    .D(_03_),
    .Q(push_1)
  );
  (* src = "referee_2_est.v:13" *)
  DFF _82_ (
    .C(clk),
    .D(_04_),
    .Q(push_2)
  );
  (* src = "referee_2_est.v:13" *)
  DFF _83_ (
    .C(clk),
    .D(_05_),
    .Q(push_3)
  );
  (* src = "referee_2_est.v:13" *)
  DFF _84_ (
    .C(clk),
    .D(_00_[0]),
    .Q(cont[0])
  );
  (* src = "referee_2_est.v:13" *)
  DFF _85_ (
    .C(clk),
    .D(_00_[1]),
    .Q(cont[1])
  );
endmodule
