/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "referee_2_str.v:3" *)
module referee_2_str(push_signal_str, pop_signal_str, data_out_str, almost_full_signal, state, almost_empty_signal, empty_f_signal, clk, data_in);
  (* src = "referee_2_str.v:21" *)
  wire [11:0] _000_;
  (* src = "referee_2_str.v:21" *)
  wire _001_;
  (* src = "referee_2_str.v:21" *)
  wire _002_;
  (* src = "referee_2_str.v:21" *)
  wire [3:0] _003_;
  (* src = "referee_2_str.v:21" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "referee_2_str.v:15" *)
  input almost_empty_signal;
  (* src = "referee_2_str.v:14" *)
  input [3:0] almost_full_signal;
  (* src = "referee_2_str.v:16" *)
  input clk;
  (* src = "referee_2_str.v:17" *)
  input [11:0] data_in;
  (* src = "referee_2_str.v:13" *)
  output [11:0] data_out_str;
  (* src = "referee_2_str.v:15" *)
  input empty_f_signal;
  (* src = "referee_2_str.v:12" *)
  output pop_signal_str;
  (* src = "referee_2_str.v:19" *)
  wire pop_toggle;
  (* src = "referee_2_str.v:11" *)
  output [3:0] push_signal_str;
  (* src = "referee_2_str.v:19" *)
  wire push_toggle;
  (* src = "referee_2_str.v:14" *)
  input [3:0] state;
  NOT _082_ (
    .A(state[3]),
    .Y(_047_)
  );
  NOT _083_ (
    .A(data_in[10]),
    .Y(_048_)
  );
  NOT _084_ (
    .A(data_in[11]),
    .Y(_049_)
  );
  NOT _085_ (
    .A(push_signal_str[3]),
    .Y(_050_)
  );
  NOT _086_ (
    .A(push_toggle),
    .Y(_051_)
  );
  NOT _087_ (
    .A(pop_toggle),
    .Y(_052_)
  );
  NOT _088_ (
    .A(data_in[0]),
    .Y(_053_)
  );
  NOT _089_ (
    .A(data_in[1]),
    .Y(_054_)
  );
  NOT _090_ (
    .A(data_in[2]),
    .Y(_055_)
  );
  NOT _091_ (
    .A(data_in[3]),
    .Y(_056_)
  );
  NOT _092_ (
    .A(data_in[4]),
    .Y(_057_)
  );
  NOT _093_ (
    .A(data_in[5]),
    .Y(_058_)
  );
  NOT _094_ (
    .A(data_in[6]),
    .Y(_059_)
  );
  NOT _095_ (
    .A(data_in[7]),
    .Y(_060_)
  );
  NOT _096_ (
    .A(data_in[8]),
    .Y(_061_)
  );
  NOT _097_ (
    .A(data_in[9]),
    .Y(_062_)
  );
  NOT _098_ (
    .A(state[0]),
    .Y(_063_)
  );
  NOR _099_ (
    .A(state[2]),
    .B(state[1]),
    .Y(_064_)
  );
  NOR _100_ (
    .A(_047_),
    .B(state[0]),
    .Y(_065_)
  );
  NAND _101_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _102_ (
    .A(push_toggle),
    .B(_052_),
    .Y(_067_)
  );
  NOR _103_ (
    .A(_051_),
    .B(_066_),
    .Y(_068_)
  );
  NOR _104_ (
    .A(_066_),
    .B(_067_),
    .Y(_069_)
  );
  NAND _105_ (
    .A(_052_),
    .B(_068_),
    .Y(_070_)
  );
  NAND _106_ (
    .A(data_in[10]),
    .B(data_in[11]),
    .Y(_071_)
  );
  NAND _107_ (
    .A(_050_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _108_ (
    .A(_069_),
    .B(_072_),
    .Y(_073_)
  );
  NOT _109_ (
    .A(_073_),
    .Y(_003_[3])
  );
  NOR _110_ (
    .A(data_in[10]),
    .B(data_in[11]),
    .Y(_074_)
  );
  NOR _111_ (
    .A(push_signal_str[0]),
    .B(_074_),
    .Y(_075_)
  );
  NAND _112_ (
    .A(_049_),
    .B(_069_),
    .Y(_076_)
  );
  NOR _113_ (
    .A(_070_),
    .B(_075_),
    .Y(_003_[0])
  );
  NOR _114_ (
    .A(data_in[10]),
    .B(_049_),
    .Y(_077_)
  );
  NOR _115_ (
    .A(push_signal_str[2]),
    .B(_077_),
    .Y(_078_)
  );
  NAND _116_ (
    .A(_048_),
    .B(_069_),
    .Y(_079_)
  );
  NOR _117_ (
    .A(_070_),
    .B(_078_),
    .Y(_003_[2])
  );
  NOR _118_ (
    .A(_048_),
    .B(data_in[11]),
    .Y(_080_)
  );
  NOR _119_ (
    .A(push_signal_str[1]),
    .B(_080_),
    .Y(_081_)
  );
  NOR _120_ (
    .A(_070_),
    .B(_081_),
    .Y(_003_[1])
  );
  NOR _121_ (
    .A(_052_),
    .B(_066_),
    .Y(_004_)
  );
  NOR _122_ (
    .A(state[3]),
    .B(_063_),
    .Y(_005_)
  );
  NAND _123_ (
    .A(_064_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _124_ (
    .A(data_out_str[0]),
    .B(_069_),
    .Y(_007_)
  );
  NAND _125_ (
    .A(_053_),
    .B(_069_),
    .Y(_008_)
  );
  NAND _126_ (
    .A(_006_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _127_ (
    .A(_007_),
    .B(_009_),
    .Y(_000_[0])
  );
  NOR _128_ (
    .A(data_out_str[1]),
    .B(_069_),
    .Y(_010_)
  );
  NAND _129_ (
    .A(_054_),
    .B(_069_),
    .Y(_011_)
  );
  NAND _130_ (
    .A(_006_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _131_ (
    .A(_010_),
    .B(_012_),
    .Y(_000_[1])
  );
  NOR _132_ (
    .A(data_out_str[2]),
    .B(_069_),
    .Y(_013_)
  );
  NAND _133_ (
    .A(_055_),
    .B(_069_),
    .Y(_014_)
  );
  NAND _134_ (
    .A(_006_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _135_ (
    .A(_013_),
    .B(_015_),
    .Y(_000_[2])
  );
  NOR _136_ (
    .A(data_out_str[3]),
    .B(_069_),
    .Y(_016_)
  );
  NAND _137_ (
    .A(_056_),
    .B(_069_),
    .Y(_017_)
  );
  NAND _138_ (
    .A(_006_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _139_ (
    .A(_016_),
    .B(_018_),
    .Y(_000_[3])
  );
  NOR _140_ (
    .A(data_out_str[4]),
    .B(_069_),
    .Y(_019_)
  );
  NAND _141_ (
    .A(_057_),
    .B(_069_),
    .Y(_020_)
  );
  NAND _142_ (
    .A(_006_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _143_ (
    .A(_019_),
    .B(_021_),
    .Y(_000_[4])
  );
  NOR _144_ (
    .A(data_out_str[5]),
    .B(_069_),
    .Y(_022_)
  );
  NAND _145_ (
    .A(_058_),
    .B(_069_),
    .Y(_023_)
  );
  NAND _146_ (
    .A(_006_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _147_ (
    .A(_022_),
    .B(_024_),
    .Y(_000_[5])
  );
  NOR _148_ (
    .A(data_out_str[6]),
    .B(_069_),
    .Y(_025_)
  );
  NAND _149_ (
    .A(_059_),
    .B(_069_),
    .Y(_026_)
  );
  NAND _150_ (
    .A(_006_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _151_ (
    .A(_025_),
    .B(_027_),
    .Y(_000_[6])
  );
  NOR _152_ (
    .A(data_out_str[7]),
    .B(_069_),
    .Y(_028_)
  );
  NAND _153_ (
    .A(_060_),
    .B(_069_),
    .Y(_029_)
  );
  NAND _154_ (
    .A(_006_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _155_ (
    .A(_028_),
    .B(_030_),
    .Y(_000_[7])
  );
  NOR _156_ (
    .A(data_out_str[8]),
    .B(_069_),
    .Y(_031_)
  );
  NAND _157_ (
    .A(_061_),
    .B(_069_),
    .Y(_032_)
  );
  NAND _158_ (
    .A(_006_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _159_ (
    .A(_031_),
    .B(_033_),
    .Y(_000_[8])
  );
  NOR _160_ (
    .A(data_out_str[9]),
    .B(_069_),
    .Y(_034_)
  );
  NAND _161_ (
    .A(_062_),
    .B(_069_),
    .Y(_035_)
  );
  NAND _162_ (
    .A(_006_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _163_ (
    .A(_034_),
    .B(_036_),
    .Y(_000_[9])
  );
  NOR _164_ (
    .A(data_out_str[10]),
    .B(_069_),
    .Y(_037_)
  );
  NAND _165_ (
    .A(_079_),
    .B(_006_),
    .Y(_038_)
  );
  NOR _166_ (
    .A(_037_),
    .B(_038_),
    .Y(_000_[10])
  );
  NOR _167_ (
    .A(data_out_str[11]),
    .B(_069_),
    .Y(_039_)
  );
  NAND _168_ (
    .A(_076_),
    .B(_006_),
    .Y(_040_)
  );
  NOR _169_ (
    .A(_039_),
    .B(_040_),
    .Y(_000_[11])
  );
  NOR _170_ (
    .A(almost_full_signal[3]),
    .B(almost_full_signal[2]),
    .Y(_041_)
  );
  NOR _171_ (
    .A(almost_full_signal[1]),
    .B(almost_full_signal[0]),
    .Y(_042_)
  );
  NOR _172_ (
    .A(empty_f_signal),
    .B(pop_toggle),
    .Y(_043_)
  );
  NAND _173_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _174_ (
    .A(_044_),
    .Y(_045_)
  );
  NAND _175_ (
    .A(_041_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _176_ (
    .A(_066_),
    .B(_046_),
    .Y(_001_)
  );
  NOR _177_ (
    .A(_066_),
    .B(_046_),
    .Y(_002_)
  );
  (* src = "referee_2_str.v:21" *)
  DFF _178_ (
    .C(clk),
    .D(_003_[0]),
    .Q(push_signal_str[0])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _179_ (
    .C(clk),
    .D(_003_[1]),
    .Q(push_signal_str[1])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _180_ (
    .C(clk),
    .D(_003_[2]),
    .Q(push_signal_str[2])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _181_ (
    .C(clk),
    .D(_003_[3]),
    .Q(push_signal_str[3])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _182_ (
    .C(clk),
    .D(_001_),
    .Q(pop_signal_str)
  );
  (* src = "referee_2_str.v:21" *)
  DFF _183_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out_str[0])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _184_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out_str[1])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _185_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out_str[2])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _186_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out_str[3])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _187_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out_str[4])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _188_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_out_str[5])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _189_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_out_str[6])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _190_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_out_str[7])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _191_ (
    .C(clk),
    .D(_000_[8]),
    .Q(data_out_str[8])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _192_ (
    .C(clk),
    .D(_000_[9]),
    .Q(data_out_str[9])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _193_ (
    .C(clk),
    .D(_000_[10]),
    .Q(data_out_str[10])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _194_ (
    .C(clk),
    .D(_000_[11]),
    .Q(data_out_str[11])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _195_ (
    .C(clk),
    .D(_004_),
    .Q(push_toggle)
  );
  (* src = "referee_2_str.v:21" *)
  DFF _196_ (
    .C(clk),
    .D(_002_),
    .Q(pop_toggle)
  );
endmodule
