/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "referee_2_str.v:3" *)
module referee_2_str(push_signal_str, pop_signal_str, data_out_str, almost_full_signal, almost_empty_signal, clk, reset, data_in);
  (* src = "referee_2_str.v:21" *)
  wire [11:0] _000_;
  (* src = "referee_2_str.v:21" *)
  wire _001_;
  (* src = "referee_2_str.v:21" *)
  wire _002_;
  (* src = "referee_2_str.v:21" *)
  wire [3:0] _003_;
  (* src = "referee_2_str.v:21" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  (* src = "referee_2_str.v:15" *)
  input almost_empty_signal;
  (* src = "referee_2_str.v:14" *)
  input [3:0] almost_full_signal;
  (* src = "referee_2_str.v:16" *)
  input clk;
  (* src = "referee_2_str.v:17" *)
  input [11:0] data_in;
  (* src = "referee_2_str.v:13" *)
  output [11:0] data_out_str;
  (* src = "referee_2_str.v:12" *)
  output pop_signal_str;
  (* src = "referee_2_str.v:19" *)
  wire pop_toggle;
  (* src = "referee_2_str.v:11" *)
  output [3:0] push_signal_str;
  (* src = "referee_2_str.v:19" *)
  wire push_toggle;
  (* src = "referee_2_str.v:16" *)
  input reset;
  NOT _074_ (
    .A(data_in[11]),
    .Y(_036_)
  );
  NOT _075_ (
    .A(data_in[10]),
    .Y(_037_)
  );
  NOT _076_ (
    .A(push_toggle),
    .Y(_038_)
  );
  NOT _077_ (
    .A(reset),
    .Y(_039_)
  );
  NOT _078_ (
    .A(data_in[0]),
    .Y(_040_)
  );
  NOT _079_ (
    .A(data_in[1]),
    .Y(_041_)
  );
  NOT _080_ (
    .A(data_in[2]),
    .Y(_042_)
  );
  NOT _081_ (
    .A(data_in[3]),
    .Y(_043_)
  );
  NOT _082_ (
    .A(data_in[4]),
    .Y(_044_)
  );
  NOT _083_ (
    .A(data_in[5]),
    .Y(_045_)
  );
  NOT _084_ (
    .A(data_in[6]),
    .Y(_046_)
  );
  NOT _085_ (
    .A(data_in[7]),
    .Y(_047_)
  );
  NOT _086_ (
    .A(data_in[8]),
    .Y(_048_)
  );
  NOT _087_ (
    .A(data_in[9]),
    .Y(_049_)
  );
  NAND _088_ (
    .A(data_in[11]),
    .B(data_in[10]),
    .Y(_050_)
  );
  NOT _089_ (
    .A(_050_),
    .Y(_051_)
  );
  NOR _090_ (
    .A(push_signal_str[3]),
    .B(_051_),
    .Y(_052_)
  );
  NOR _091_ (
    .A(_038_),
    .B(pop_toggle),
    .Y(_053_)
  );
  NAND _092_ (
    .A(reset),
    .B(_053_),
    .Y(_054_)
  );
  NOR _093_ (
    .A(_052_),
    .B(_054_),
    .Y(_003_[3])
  );
  NOR _094_ (
    .A(data_in[11]),
    .B(_037_),
    .Y(_055_)
  );
  NOR _095_ (
    .A(push_signal_str[1]),
    .B(_055_),
    .Y(_056_)
  );
  NOR _096_ (
    .A(_054_),
    .B(_056_),
    .Y(_003_[1])
  );
  NOR _097_ (
    .A(data_in[11]),
    .B(data_in[10]),
    .Y(_057_)
  );
  NOR _098_ (
    .A(push_signal_str[0]),
    .B(_057_),
    .Y(_058_)
  );
  NOR _099_ (
    .A(_054_),
    .B(_058_),
    .Y(_003_[0])
  );
  NOR _100_ (
    .A(_036_),
    .B(data_in[10]),
    .Y(_059_)
  );
  NOR _101_ (
    .A(push_signal_str[2]),
    .B(_059_),
    .Y(_060_)
  );
  NOR _102_ (
    .A(_054_),
    .B(_060_),
    .Y(_003_[2])
  );
  NOR _103_ (
    .A(almost_full_signal[1]),
    .B(almost_full_signal[0]),
    .Y(_061_)
  );
  NOR _104_ (
    .A(pop_toggle),
    .B(almost_full_signal[3]),
    .Y(_062_)
  );
  NOT _105_ (
    .A(_062_),
    .Y(_063_)
  );
  NOR _106_ (
    .A(almost_empty_signal),
    .B(almost_full_signal[2]),
    .Y(_064_)
  );
  NAND _107_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _108_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  NOT _109_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _110_ (
    .A(data_out_str[0]),
    .B(_066_),
    .Y(_068_)
  );
  NAND _111_ (
    .A(_040_),
    .B(_066_),
    .Y(_069_)
  );
  NAND _112_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NOR _113_ (
    .A(_068_),
    .B(_070_),
    .Y(_000_[0])
  );
  NOR _114_ (
    .A(data_out_str[1]),
    .B(_066_),
    .Y(_071_)
  );
  NAND _115_ (
    .A(_041_),
    .B(_066_),
    .Y(_072_)
  );
  NAND _116_ (
    .A(reset),
    .B(_072_),
    .Y(_073_)
  );
  NOR _117_ (
    .A(_071_),
    .B(_073_),
    .Y(_000_[1])
  );
  NOR _118_ (
    .A(data_out_str[2]),
    .B(_066_),
    .Y(_005_)
  );
  NAND _119_ (
    .A(_042_),
    .B(_066_),
    .Y(_006_)
  );
  NAND _120_ (
    .A(reset),
    .B(_006_),
    .Y(_007_)
  );
  NOR _121_ (
    .A(_005_),
    .B(_007_),
    .Y(_000_[2])
  );
  NOR _122_ (
    .A(data_out_str[3]),
    .B(_066_),
    .Y(_008_)
  );
  NAND _123_ (
    .A(_043_),
    .B(_066_),
    .Y(_009_)
  );
  NAND _124_ (
    .A(reset),
    .B(_009_),
    .Y(_010_)
  );
  NOR _125_ (
    .A(_008_),
    .B(_010_),
    .Y(_000_[3])
  );
  NOR _126_ (
    .A(data_out_str[4]),
    .B(_066_),
    .Y(_011_)
  );
  NAND _127_ (
    .A(_044_),
    .B(_066_),
    .Y(_012_)
  );
  NAND _128_ (
    .A(reset),
    .B(_012_),
    .Y(_013_)
  );
  NOR _129_ (
    .A(_011_),
    .B(_013_),
    .Y(_000_[4])
  );
  NOR _130_ (
    .A(data_out_str[5]),
    .B(_066_),
    .Y(_014_)
  );
  NAND _131_ (
    .A(_045_),
    .B(_066_),
    .Y(_015_)
  );
  NAND _132_ (
    .A(reset),
    .B(_015_),
    .Y(_016_)
  );
  NOR _133_ (
    .A(_014_),
    .B(_016_),
    .Y(_000_[5])
  );
  NOR _134_ (
    .A(data_out_str[6]),
    .B(_066_),
    .Y(_017_)
  );
  NAND _135_ (
    .A(_046_),
    .B(_066_),
    .Y(_018_)
  );
  NAND _136_ (
    .A(reset),
    .B(_018_),
    .Y(_019_)
  );
  NOR _137_ (
    .A(_017_),
    .B(_019_),
    .Y(_000_[6])
  );
  NOR _138_ (
    .A(data_out_str[7]),
    .B(_066_),
    .Y(_020_)
  );
  NAND _139_ (
    .A(_047_),
    .B(_066_),
    .Y(_021_)
  );
  NAND _140_ (
    .A(reset),
    .B(_021_),
    .Y(_022_)
  );
  NOR _141_ (
    .A(_020_),
    .B(_022_),
    .Y(_000_[7])
  );
  NOR _142_ (
    .A(data_out_str[8]),
    .B(_066_),
    .Y(_023_)
  );
  NAND _143_ (
    .A(_048_),
    .B(_066_),
    .Y(_024_)
  );
  NAND _144_ (
    .A(reset),
    .B(_024_),
    .Y(_025_)
  );
  NOR _145_ (
    .A(_023_),
    .B(_025_),
    .Y(_000_[8])
  );
  NOR _146_ (
    .A(data_out_str[9]),
    .B(_066_),
    .Y(_026_)
  );
  NAND _147_ (
    .A(_049_),
    .B(_066_),
    .Y(_027_)
  );
  NAND _148_ (
    .A(reset),
    .B(_027_),
    .Y(_028_)
  );
  NOR _149_ (
    .A(_026_),
    .B(_028_),
    .Y(_000_[9])
  );
  NOR _150_ (
    .A(data_out_str[10]),
    .B(_066_),
    .Y(_029_)
  );
  NAND _151_ (
    .A(_037_),
    .B(_066_),
    .Y(_030_)
  );
  NAND _152_ (
    .A(reset),
    .B(_030_),
    .Y(_031_)
  );
  NOR _153_ (
    .A(_029_),
    .B(_031_),
    .Y(_000_[10])
  );
  NOR _154_ (
    .A(data_out_str[11]),
    .B(_066_),
    .Y(_032_)
  );
  NAND _155_ (
    .A(_036_),
    .B(_066_),
    .Y(_033_)
  );
  NAND _156_ (
    .A(reset),
    .B(_033_),
    .Y(_034_)
  );
  NOR _157_ (
    .A(_032_),
    .B(_034_),
    .Y(_000_[11])
  );
  NOR _158_ (
    .A(_039_),
    .B(_067_),
    .Y(_001_)
  );
  NAND _159_ (
    .A(pop_toggle),
    .B(reset),
    .Y(_035_)
  );
  NOT _160_ (
    .A(_035_),
    .Y(_004_)
  );
  NOR _161_ (
    .A(_039_),
    .B(_067_),
    .Y(_002_)
  );
  (* src = "referee_2_str.v:21" *)
  DFF _162_ (
    .C(clk),
    .D(_004_),
    .Q(push_toggle)
  );
  (* src = "referee_2_str.v:21" *)
  DFF _163_ (
    .C(clk),
    .D(_003_[0]),
    .Q(push_signal_str[0])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _164_ (
    .C(clk),
    .D(_003_[1]),
    .Q(push_signal_str[1])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _165_ (
    .C(clk),
    .D(_003_[2]),
    .Q(push_signal_str[2])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _166_ (
    .C(clk),
    .D(_003_[3]),
    .Q(push_signal_str[3])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _167_ (
    .C(clk),
    .D(_001_),
    .Q(pop_signal_str)
  );
  (* src = "referee_2_str.v:21" *)
  DFF _168_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out_str[0])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _169_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out_str[1])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _170_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out_str[2])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _171_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out_str[3])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _172_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out_str[4])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _173_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_out_str[5])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _174_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_out_str[6])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _175_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_out_str[7])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _176_ (
    .C(clk),
    .D(_000_[8]),
    .Q(data_out_str[8])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _177_ (
    .C(clk),
    .D(_000_[9]),
    .Q(data_out_str[9])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _178_ (
    .C(clk),
    .D(_000_[10]),
    .Q(data_out_str[10])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _179_ (
    .C(clk),
    .D(_000_[11]),
    .Q(data_out_str[11])
  );
  (* src = "referee_2_str.v:21" *)
  DFF _180_ (
    .C(clk),
    .D(_002_),
    .Q(pop_toggle)
  );
endmodule
