/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador_est.v:1" *)
module contador_est(data_in, reset, clk, cuenta_est);
  (* src = "contador_est.v:10" *)
  wire [15:0] _000_;
  (* src = "contador_est.v:10" *)
  wire [11:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  (* src = "contador_est.v:4" *)
  input clk;
  (* src = "contador_est.v:5" *)
  output [15:0] cuenta_est;
  (* src = "contador_est.v:2" *)
  input [11:0] data_in;
  (* src = "contador_est.v:7" *)
  wire [11:0] detector;
  (* src = "contador_est.v:3" *)
  input reset;
  NOT _205_ (
    .A(cuenta_est[5]),
    .Y(_175_)
  );
  NOT _206_ (
    .A(cuenta_est[7]),
    .Y(_176_)
  );
  NOT _207_ (
    .A(cuenta_est[9]),
    .Y(_177_)
  );
  NOT _208_ (
    .A(cuenta_est[10]),
    .Y(_178_)
  );
  NOT _209_ (
    .A(cuenta_est[11]),
    .Y(_179_)
  );
  NOT _210_ (
    .A(cuenta_est[12]),
    .Y(_180_)
  );
  NOT _211_ (
    .A(cuenta_est[13]),
    .Y(_181_)
  );
  NOT _212_ (
    .A(cuenta_est[14]),
    .Y(_182_)
  );
  NOT _213_ (
    .A(cuenta_est[15]),
    .Y(_183_)
  );
  NOT _214_ (
    .A(reset),
    .Y(_184_)
  );
  NOT _215_ (
    .A(detector[1]),
    .Y(_185_)
  );
  NOT _216_ (
    .A(data_in[1]),
    .Y(_186_)
  );
  NOT _217_ (
    .A(detector[2]),
    .Y(_187_)
  );
  NOT _218_ (
    .A(data_in[2]),
    .Y(_188_)
  );
  NOT _219_ (
    .A(detector[5]),
    .Y(_189_)
  );
  NOT _220_ (
    .A(data_in[5]),
    .Y(_190_)
  );
  NOT _221_ (
    .A(detector[6]),
    .Y(_191_)
  );
  NOT _222_ (
    .A(data_in[6]),
    .Y(_192_)
  );
  NOT _223_ (
    .A(detector[11]),
    .Y(_193_)
  );
  NOT _224_ (
    .A(data_in[11]),
    .Y(_194_)
  );
  NOT _225_ (
    .A(cuenta_est[0]),
    .Y(_195_)
  );
  NOT _226_ (
    .A(cuenta_est[1]),
    .Y(_196_)
  );
  NOT _227_ (
    .A(cuenta_est[3]),
    .Y(_197_)
  );
  NAND _228_ (
    .A(detector[7]),
    .B(data_in[7]),
    .Y(_198_)
  );
  NOT _229_ (
    .A(_198_),
    .Y(_199_)
  );
  NOR _230_ (
    .A(detector[7]),
    .B(data_in[7]),
    .Y(_200_)
  );
  NOT _231_ (
    .A(_200_),
    .Y(_201_)
  );
  NAND _232_ (
    .A(_198_),
    .B(_201_),
    .Y(_202_)
  );
  NOR _233_ (
    .A(_199_),
    .B(_200_),
    .Y(_203_)
  );
  NOR _234_ (
    .A(detector[10]),
    .B(data_in[10]),
    .Y(_204_)
  );
  NOT _235_ (
    .A(_204_),
    .Y(_002_)
  );
  NAND _236_ (
    .A(detector[10]),
    .B(data_in[10]),
    .Y(_003_)
  );
  NAND _237_ (
    .A(_002_),
    .B(_003_),
    .Y(_004_)
  );
  NAND _238_ (
    .A(_202_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _239_ (
    .A(detector[9]),
    .B(data_in[9]),
    .Y(_006_)
  );
  NOT _240_ (
    .A(_006_),
    .Y(_007_)
  );
  NOR _241_ (
    .A(detector[9]),
    .B(data_in[9]),
    .Y(_008_)
  );
  NOT _242_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _243_ (
    .A(_006_),
    .B(_009_),
    .Y(_010_)
  );
  NOR _244_ (
    .A(_007_),
    .B(_008_),
    .Y(_011_)
  );
  NAND _245_ (
    .A(detector[6]),
    .B(_192_),
    .Y(_012_)
  );
  NAND _246_ (
    .A(_191_),
    .B(data_in[6]),
    .Y(_013_)
  );
  NAND _247_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _248_ (
    .A(_189_),
    .B(data_in[5]),
    .Y(_015_)
  );
  NAND _249_ (
    .A(detector[5]),
    .B(_190_),
    .Y(_016_)
  );
  NOR _250_ (
    .A(detector[5]),
    .B(_190_),
    .Y(_017_)
  );
  NAND _251_ (
    .A(_189_),
    .B(data_in[5]),
    .Y(_018_)
  );
  NOR _252_ (
    .A(_015_),
    .B(_017_),
    .Y(_019_)
  );
  NAND _253_ (
    .A(_016_),
    .B(_018_),
    .Y(_020_)
  );
  NOR _254_ (
    .A(_193_),
    .B(data_in[11]),
    .Y(_021_)
  );
  NAND _255_ (
    .A(detector[11]),
    .B(_194_),
    .Y(_022_)
  );
  NOR _256_ (
    .A(detector[11]),
    .B(_194_),
    .Y(_023_)
  );
  NAND _257_ (
    .A(_193_),
    .B(data_in[11]),
    .Y(_024_)
  );
  NOR _258_ (
    .A(_021_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _259_ (
    .A(_022_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _260_ (
    .A(detector[3]),
    .B(data_in[3]),
    .Y(_027_)
  );
  NOT _261_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _262_ (
    .A(detector[3]),
    .B(data_in[3]),
    .Y(_029_)
  );
  NOT _263_ (
    .A(_029_),
    .Y(_030_)
  );
  NAND _264_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _265_ (
    .A(_028_),
    .B(_029_),
    .Y(_032_)
  );
  NOR _266_ (
    .A(_187_),
    .B(data_in[2]),
    .Y(_033_)
  );
  NAND _267_ (
    .A(detector[2]),
    .B(_188_),
    .Y(_034_)
  );
  NOR _268_ (
    .A(detector[2]),
    .B(_188_),
    .Y(_035_)
  );
  NAND _269_ (
    .A(_187_),
    .B(data_in[2]),
    .Y(_036_)
  );
  NOR _270_ (
    .A(_033_),
    .B(_035_),
    .Y(_037_)
  );
  NAND _271_ (
    .A(_034_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _272_ (
    .A(detector[4]),
    .B(data_in[4]),
    .Y(_039_)
  );
  NOT _273_ (
    .A(_039_),
    .Y(_040_)
  );
  NOR _274_ (
    .A(detector[4]),
    .B(data_in[4]),
    .Y(_041_)
  );
  NOT _275_ (
    .A(_041_),
    .Y(_042_)
  );
  NAND _276_ (
    .A(_039_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _277_ (
    .A(_040_),
    .B(_041_),
    .Y(_044_)
  );
  NAND _278_ (
    .A(detector[0]),
    .B(data_in[0]),
    .Y(_045_)
  );
  NOT _279_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _280_ (
    .A(detector[0]),
    .B(data_in[0]),
    .Y(_047_)
  );
  NOT _281_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _282_ (
    .A(_045_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _283_ (
    .A(_046_),
    .B(_047_),
    .Y(_050_)
  );
  NOR _284_ (
    .A(_185_),
    .B(data_in[1]),
    .Y(_051_)
  );
  NAND _285_ (
    .A(detector[1]),
    .B(_186_),
    .Y(_052_)
  );
  NOR _286_ (
    .A(detector[1]),
    .B(_186_),
    .Y(_053_)
  );
  NAND _287_ (
    .A(_185_),
    .B(data_in[1]),
    .Y(_054_)
  );
  NOR _288_ (
    .A(_051_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _289_ (
    .A(_052_),
    .B(_054_),
    .Y(_056_)
  );
  NAND _290_ (
    .A(detector[8]),
    .B(data_in[8]),
    .Y(_057_)
  );
  NOT _291_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _292_ (
    .A(detector[8]),
    .B(data_in[8]),
    .Y(_059_)
  );
  NOT _293_ (
    .A(_059_),
    .Y(_060_)
  );
  NAND _294_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _295_ (
    .A(_058_),
    .B(_059_),
    .Y(_062_)
  );
  NOR _296_ (
    .A(_038_),
    .B(_056_),
    .Y(_063_)
  );
  NAND _297_ (
    .A(_037_),
    .B(_055_),
    .Y(_064_)
  );
  NOR _298_ (
    .A(_014_),
    .B(_026_),
    .Y(_065_)
  );
  NAND _299_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _300_ (
    .A(_032_),
    .B(_044_),
    .Y(_067_)
  );
  NAND _301_ (
    .A(_031_),
    .B(_043_),
    .Y(_068_)
  );
  NOR _302_ (
    .A(_020_),
    .B(_062_),
    .Y(_069_)
  );
  NAND _303_ (
    .A(_019_),
    .B(_061_),
    .Y(_070_)
  );
  NAND _304_ (
    .A(_067_),
    .B(_069_),
    .Y(_071_)
  );
  NOR _305_ (
    .A(_066_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _306_ (
    .A(_010_),
    .B(_049_),
    .Y(_073_)
  );
  NOR _307_ (
    .A(_005_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _308_ (
    .A(_011_),
    .B(_068_),
    .Y(_075_)
  );
  NOR _309_ (
    .A(_050_),
    .B(_064_),
    .Y(_076_)
  );
  NAND _310_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _311_ (
    .A(_203_),
    .B(_014_),
    .Y(_078_)
  );
  NAND _312_ (
    .A(_004_),
    .B(_025_),
    .Y(_079_)
  );
  NOR _313_ (
    .A(_070_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _314_ (
    .A(_078_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _315_ (
    .A(_077_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _316_ (
    .A(_072_),
    .B(_074_),
    .Y(_083_)
  );
  NOR _317_ (
    .A(_195_),
    .B(_082_),
    .Y(_084_)
  );
  NOT _318_ (
    .A(_084_),
    .Y(_085_)
  );
  NAND _319_ (
    .A(_195_),
    .B(_082_),
    .Y(_086_)
  );
  NAND _320_ (
    .A(reset),
    .B(_086_),
    .Y(_087_)
  );
  NOR _321_ (
    .A(_084_),
    .B(_087_),
    .Y(_000_[0])
  );
  NOR _322_ (
    .A(_196_),
    .B(_085_),
    .Y(_088_)
  );
  NOR _323_ (
    .A(cuenta_est[1]),
    .B(_084_),
    .Y(_089_)
  );
  NOT _324_ (
    .A(_089_),
    .Y(_090_)
  );
  NAND _325_ (
    .A(reset),
    .B(_090_),
    .Y(_091_)
  );
  NOR _326_ (
    .A(_088_),
    .B(_091_),
    .Y(_000_[1])
  );
  NAND _327_ (
    .A(cuenta_est[1]),
    .B(cuenta_est[2]),
    .Y(_092_)
  );
  NAND _328_ (
    .A(cuenta_est[2]),
    .B(_088_),
    .Y(_093_)
  );
  NOR _329_ (
    .A(cuenta_est[2]),
    .B(_088_),
    .Y(_094_)
  );
  NAND _330_ (
    .A(reset),
    .B(_093_),
    .Y(_095_)
  );
  NOR _331_ (
    .A(_094_),
    .B(_095_),
    .Y(_000_[2])
  );
  NOR _332_ (
    .A(_197_),
    .B(_092_),
    .Y(_096_)
  );
  NOR _333_ (
    .A(_197_),
    .B(_093_),
    .Y(_097_)
  );
  NAND _334_ (
    .A(_197_),
    .B(_093_),
    .Y(_098_)
  );
  NAND _335_ (
    .A(reset),
    .B(_098_),
    .Y(_099_)
  );
  NOR _336_ (
    .A(_097_),
    .B(_099_),
    .Y(_000_[3])
  );
  NOR _337_ (
    .A(cuenta_est[4]),
    .B(_097_),
    .Y(_100_)
  );
  NAND _338_ (
    .A(cuenta_est[4]),
    .B(_096_),
    .Y(_101_)
  );
  NOR _339_ (
    .A(_195_),
    .B(_101_),
    .Y(_102_)
  );
  NOT _340_ (
    .A(_102_),
    .Y(_103_)
  );
  NOR _341_ (
    .A(_082_),
    .B(_103_),
    .Y(_104_)
  );
  NAND _342_ (
    .A(_083_),
    .B(_102_),
    .Y(_105_)
  );
  NAND _343_ (
    .A(reset),
    .B(_105_),
    .Y(_106_)
  );
  NOR _344_ (
    .A(_100_),
    .B(_106_),
    .Y(_000_[4])
  );
  NOR _345_ (
    .A(_175_),
    .B(_105_),
    .Y(_107_)
  );
  NAND _346_ (
    .A(_175_),
    .B(_105_),
    .Y(_108_)
  );
  NAND _347_ (
    .A(reset),
    .B(_108_),
    .Y(_109_)
  );
  NOR _348_ (
    .A(_107_),
    .B(_109_),
    .Y(_000_[5])
  );
  NOR _349_ (
    .A(cuenta_est[6]),
    .B(_107_),
    .Y(_110_)
  );
  NAND _350_ (
    .A(cuenta_est[5]),
    .B(cuenta_est[6]),
    .Y(_111_)
  );
  NAND _351_ (
    .A(cuenta_est[6]),
    .B(_107_),
    .Y(_112_)
  );
  NAND _352_ (
    .A(reset),
    .B(_112_),
    .Y(_113_)
  );
  NOR _353_ (
    .A(_110_),
    .B(_113_),
    .Y(_000_[6])
  );
  NOR _354_ (
    .A(_176_),
    .B(_112_),
    .Y(_114_)
  );
  NAND _355_ (
    .A(_176_),
    .B(_112_),
    .Y(_115_)
  );
  NAND _356_ (
    .A(reset),
    .B(_115_),
    .Y(_116_)
  );
  NOR _357_ (
    .A(_114_),
    .B(_116_),
    .Y(_000_[7])
  );
  NOR _358_ (
    .A(cuenta_est[8]),
    .B(_114_),
    .Y(_117_)
  );
  NAND _359_ (
    .A(cuenta_est[7]),
    .B(cuenta_est[8]),
    .Y(_118_)
  );
  NOT _360_ (
    .A(_118_),
    .Y(_119_)
  );
  NOR _361_ (
    .A(_111_),
    .B(_118_),
    .Y(_120_)
  );
  NOT _362_ (
    .A(_120_),
    .Y(_121_)
  );
  NOR _363_ (
    .A(_105_),
    .B(_121_),
    .Y(_122_)
  );
  NAND _364_ (
    .A(_104_),
    .B(_120_),
    .Y(_123_)
  );
  NAND _365_ (
    .A(reset),
    .B(_123_),
    .Y(_124_)
  );
  NOR _366_ (
    .A(_117_),
    .B(_124_),
    .Y(_000_[8])
  );
  NOR _367_ (
    .A(_177_),
    .B(_123_),
    .Y(_125_)
  );
  NAND _368_ (
    .A(cuenta_est[9]),
    .B(_122_),
    .Y(_126_)
  );
  NOR _369_ (
    .A(cuenta_est[9]),
    .B(_122_),
    .Y(_127_)
  );
  NOR _370_ (
    .A(_184_),
    .B(_127_),
    .Y(_128_)
  );
  NAND _371_ (
    .A(_126_),
    .B(_128_),
    .Y(_129_)
  );
  NOT _372_ (
    .A(_129_),
    .Y(_000_[9])
  );
  NAND _373_ (
    .A(cuenta_est[9]),
    .B(_119_),
    .Y(_130_)
  );
  NAND _374_ (
    .A(_178_),
    .B(_126_),
    .Y(_131_)
  );
  NAND _375_ (
    .A(cuenta_est[9]),
    .B(cuenta_est[10]),
    .Y(_132_)
  );
  NOT _376_ (
    .A(_132_),
    .Y(_133_)
  );
  NAND _377_ (
    .A(reset),
    .B(_131_),
    .Y(_134_)
  );
  NAND _378_ (
    .A(cuenta_est[10]),
    .B(_125_),
    .Y(_135_)
  );
  NOT _379_ (
    .A(_135_),
    .Y(_136_)
  );
  NOR _380_ (
    .A(_134_),
    .B(_136_),
    .Y(_000_[10])
  );
  NOR _381_ (
    .A(cuenta_est[11]),
    .B(_136_),
    .Y(_137_)
  );
  NAND _382_ (
    .A(cuenta_est[11]),
    .B(_133_),
    .Y(_138_)
  );
  NOR _383_ (
    .A(_121_),
    .B(_138_),
    .Y(_139_)
  );
  NAND _384_ (
    .A(_104_),
    .B(_139_),
    .Y(_140_)
  );
  NAND _385_ (
    .A(reset),
    .B(_140_),
    .Y(_141_)
  );
  NOR _386_ (
    .A(_137_),
    .B(_141_),
    .Y(_000_[11])
  );
  NOR _387_ (
    .A(_179_),
    .B(_111_),
    .Y(_142_)
  );
  NAND _388_ (
    .A(_102_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _389_ (
    .A(_130_),
    .B(_143_),
    .Y(_144_)
  );
  NAND _390_ (
    .A(cuenta_est[10]),
    .B(_144_),
    .Y(_145_)
  );
  NOR _391_ (
    .A(_082_),
    .B(_145_),
    .Y(_146_)
  );
  NAND _392_ (
    .A(_180_),
    .B(_140_),
    .Y(_147_)
  );
  NAND _393_ (
    .A(reset),
    .B(_147_),
    .Y(_148_)
  );
  NOR _394_ (
    .A(_180_),
    .B(_140_),
    .Y(_149_)
  );
  NAND _395_ (
    .A(cuenta_est[12]),
    .B(_146_),
    .Y(_150_)
  );
  NOR _396_ (
    .A(_148_),
    .B(_149_),
    .Y(_000_[12])
  );
  NOR _397_ (
    .A(cuenta_est[13]),
    .B(_149_),
    .Y(_151_)
  );
  NOR _398_ (
    .A(_184_),
    .B(_151_),
    .Y(_152_)
  );
  NAND _399_ (
    .A(cuenta_est[13]),
    .B(_149_),
    .Y(_153_)
  );
  NOR _400_ (
    .A(_181_),
    .B(_150_),
    .Y(_154_)
  );
  NAND _401_ (
    .A(_152_),
    .B(_153_),
    .Y(_155_)
  );
  NOT _402_ (
    .A(_155_),
    .Y(_000_[13])
  );
  NAND _403_ (
    .A(_182_),
    .B(_153_),
    .Y(_156_)
  );
  NAND _404_ (
    .A(reset),
    .B(_156_),
    .Y(_157_)
  );
  NOR _405_ (
    .A(_182_),
    .B(_153_),
    .Y(_158_)
  );
  NAND _406_ (
    .A(cuenta_est[14]),
    .B(_154_),
    .Y(_159_)
  );
  NOR _407_ (
    .A(_157_),
    .B(_158_),
    .Y(_000_[14])
  );
  NAND _408_ (
    .A(_183_),
    .B(_159_),
    .Y(_160_)
  );
  NAND _409_ (
    .A(reset),
    .B(_160_),
    .Y(_161_)
  );
  NOR _410_ (
    .A(_183_),
    .B(_159_),
    .Y(_162_)
  );
  NOR _411_ (
    .A(_161_),
    .B(_162_),
    .Y(_000_[15])
  );
  NAND _412_ (
    .A(reset),
    .B(data_in[0]),
    .Y(_163_)
  );
  NOT _413_ (
    .A(_163_),
    .Y(_001_[0])
  );
  NAND _414_ (
    .A(reset),
    .B(data_in[1]),
    .Y(_164_)
  );
  NOT _415_ (
    .A(_164_),
    .Y(_001_[1])
  );
  NAND _416_ (
    .A(reset),
    .B(data_in[2]),
    .Y(_165_)
  );
  NOT _417_ (
    .A(_165_),
    .Y(_001_[2])
  );
  NAND _418_ (
    .A(reset),
    .B(data_in[3]),
    .Y(_166_)
  );
  NOT _419_ (
    .A(_166_),
    .Y(_001_[3])
  );
  NAND _420_ (
    .A(reset),
    .B(data_in[4]),
    .Y(_167_)
  );
  NOT _421_ (
    .A(_167_),
    .Y(_001_[4])
  );
  NAND _422_ (
    .A(reset),
    .B(data_in[5]),
    .Y(_168_)
  );
  NOT _423_ (
    .A(_168_),
    .Y(_001_[5])
  );
  NAND _424_ (
    .A(reset),
    .B(data_in[6]),
    .Y(_169_)
  );
  NOT _425_ (
    .A(_169_),
    .Y(_001_[6])
  );
  NAND _426_ (
    .A(reset),
    .B(data_in[7]),
    .Y(_170_)
  );
  NOT _427_ (
    .A(_170_),
    .Y(_001_[7])
  );
  NAND _428_ (
    .A(reset),
    .B(data_in[8]),
    .Y(_171_)
  );
  NOT _429_ (
    .A(_171_),
    .Y(_001_[8])
  );
  NAND _430_ (
    .A(reset),
    .B(data_in[9]),
    .Y(_172_)
  );
  NOT _431_ (
    .A(_172_),
    .Y(_001_[9])
  );
  NAND _432_ (
    .A(reset),
    .B(data_in[10]),
    .Y(_173_)
  );
  NOT _433_ (
    .A(_173_),
    .Y(_001_[10])
  );
  NAND _434_ (
    .A(reset),
    .B(data_in[11]),
    .Y(_174_)
  );
  NOT _435_ (
    .A(_174_),
    .Y(_001_[11])
  );
  (* src = "contador_est.v:10" *)
  DFF _436_ (
    .C(clk),
    .D(_001_[0]),
    .Q(detector[0])
  );
  (* src = "contador_est.v:10" *)
  DFF _437_ (
    .C(clk),
    .D(_001_[1]),
    .Q(detector[1])
  );
  (* src = "contador_est.v:10" *)
  DFF _438_ (
    .C(clk),
    .D(_001_[2]),
    .Q(detector[2])
  );
  (* src = "contador_est.v:10" *)
  DFF _439_ (
    .C(clk),
    .D(_001_[3]),
    .Q(detector[3])
  );
  (* src = "contador_est.v:10" *)
  DFF _440_ (
    .C(clk),
    .D(_001_[4]),
    .Q(detector[4])
  );
  (* src = "contador_est.v:10" *)
  DFF _441_ (
    .C(clk),
    .D(_001_[5]),
    .Q(detector[5])
  );
  (* src = "contador_est.v:10" *)
  DFF _442_ (
    .C(clk),
    .D(_001_[6]),
    .Q(detector[6])
  );
  (* src = "contador_est.v:10" *)
  DFF _443_ (
    .C(clk),
    .D(_001_[7]),
    .Q(detector[7])
  );
  (* src = "contador_est.v:10" *)
  DFF _444_ (
    .C(clk),
    .D(_001_[8]),
    .Q(detector[8])
  );
  (* src = "contador_est.v:10" *)
  DFF _445_ (
    .C(clk),
    .D(_001_[9]),
    .Q(detector[9])
  );
  (* src = "contador_est.v:10" *)
  DFF _446_ (
    .C(clk),
    .D(_001_[10]),
    .Q(detector[10])
  );
  (* src = "contador_est.v:10" *)
  DFF _447_ (
    .C(clk),
    .D(_001_[11]),
    .Q(detector[11])
  );
  (* src = "contador_est.v:10" *)
  DFF _448_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cuenta_est[0])
  );
  (* src = "contador_est.v:10" *)
  DFF _449_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cuenta_est[1])
  );
  (* src = "contador_est.v:10" *)
  DFF _450_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cuenta_est[2])
  );
  (* src = "contador_est.v:10" *)
  DFF _451_ (
    .C(clk),
    .D(_000_[3]),
    .Q(cuenta_est[3])
  );
  (* src = "contador_est.v:10" *)
  DFF _452_ (
    .C(clk),
    .D(_000_[4]),
    .Q(cuenta_est[4])
  );
  (* src = "contador_est.v:10" *)
  DFF _453_ (
    .C(clk),
    .D(_000_[5]),
    .Q(cuenta_est[5])
  );
  (* src = "contador_est.v:10" *)
  DFF _454_ (
    .C(clk),
    .D(_000_[6]),
    .Q(cuenta_est[6])
  );
  (* src = "contador_est.v:10" *)
  DFF _455_ (
    .C(clk),
    .D(_000_[7]),
    .Q(cuenta_est[7])
  );
  (* src = "contador_est.v:10" *)
  DFF _456_ (
    .C(clk),
    .D(_000_[8]),
    .Q(cuenta_est[8])
  );
  (* src = "contador_est.v:10" *)
  DFF _457_ (
    .C(clk),
    .D(_000_[9]),
    .Q(cuenta_est[9])
  );
  (* src = "contador_est.v:10" *)
  DFF _458_ (
    .C(clk),
    .D(_000_[10]),
    .Q(cuenta_est[10])
  );
  (* src = "contador_est.v:10" *)
  DFF _459_ (
    .C(clk),
    .D(_000_[11]),
    .Q(cuenta_est[11])
  );
  (* src = "contador_est.v:10" *)
  DFF _460_ (
    .C(clk),
    .D(_000_[12]),
    .Q(cuenta_est[12])
  );
  (* src = "contador_est.v:10" *)
  DFF _461_ (
    .C(clk),
    .D(_000_[13]),
    .Q(cuenta_est[13])
  );
  (* src = "contador_est.v:10" *)
  DFF _462_ (
    .C(clk),
    .D(_000_[14]),
    .Q(cuenta_est[14])
  );
  (* src = "contador_est.v:10" *)
  DFF _463_ (
    .C(clk),
    .D(_000_[15]),
    .Q(cuenta_est[15])
  );
endmodule
