/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador_est.v:1" *)
module contador_est(data_in, state, clk, reset, cuenta_est);
  (* src = "contador_est.v:10" *)
  wire [4:0] _000_;
  (* src = "contador_est.v:10" *)
  wire [11:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  (* src = "contador_est.v:4" *)
  input clk;
  (* src = "contador_est.v:5" *)
  output [4:0] cuenta_est;
  (* src = "contador_est.v:2" *)
  input [11:0] data_in;
  (* src = "contador_est.v:7" *)
  wire [11:0] detector;
  (* src = "contador_est.v:4" *)
  input reset;
  (* src = "contador_est.v:3" *)
  input [3:0] state;
  NOT _101_ (
    .A(detector[0]),
    .Y(_064_)
  );
  NOT _102_ (
    .A(data_in[0]),
    .Y(_065_)
  );
  NOT _103_ (
    .A(detector[1]),
    .Y(_066_)
  );
  NOT _104_ (
    .A(data_in[1]),
    .Y(_067_)
  );
  NOT _105_ (
    .A(detector[2]),
    .Y(_068_)
  );
  NOT _106_ (
    .A(data_in[2]),
    .Y(_069_)
  );
  NOT _107_ (
    .A(detector[3]),
    .Y(_070_)
  );
  NOT _108_ (
    .A(data_in[3]),
    .Y(_071_)
  );
  NOT _109_ (
    .A(detector[4]),
    .Y(_072_)
  );
  NOT _110_ (
    .A(data_in[4]),
    .Y(_073_)
  );
  NOT _111_ (
    .A(detector[5]),
    .Y(_074_)
  );
  NOT _112_ (
    .A(data_in[5]),
    .Y(_075_)
  );
  NOT _113_ (
    .A(detector[6]),
    .Y(_076_)
  );
  NOT _114_ (
    .A(data_in[6]),
    .Y(_077_)
  );
  NOT _115_ (
    .A(detector[7]),
    .Y(_078_)
  );
  NOT _116_ (
    .A(data_in[7]),
    .Y(_079_)
  );
  NOT _117_ (
    .A(data_in[8]),
    .Y(_080_)
  );
  NOT _118_ (
    .A(data_in[9]),
    .Y(_081_)
  );
  NOT _119_ (
    .A(data_in[10]),
    .Y(_082_)
  );
  NOT _120_ (
    .A(detector[11]),
    .Y(_083_)
  );
  NOT _121_ (
    .A(data_in[11]),
    .Y(_084_)
  );
  NOT _122_ (
    .A(cuenta_est[0]),
    .Y(_085_)
  );
  NOT _123_ (
    .A(cuenta_est[2]),
    .Y(_086_)
  );
  NOT _124_ (
    .A(cuenta_est[4]),
    .Y(_087_)
  );
  NOT _125_ (
    .A(state[1]),
    .Y(_088_)
  );
  NOT _126_ (
    .A(state[0]),
    .Y(_089_)
  );
  NOR _127_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_090_)
  );
  NOT _128_ (
    .A(_090_),
    .Y(_091_)
  );
  NOR _129_ (
    .A(state[1]),
    .B(_089_),
    .Y(_092_)
  );
  NAND _130_ (
    .A(_088_),
    .B(state[0]),
    .Y(_093_)
  );
  NOR _131_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  NAND _132_ (
    .A(_090_),
    .B(_092_),
    .Y(_095_)
  );
  NOR _133_ (
    .A(_065_),
    .B(_094_),
    .Y(_001_[0])
  );
  NOR _134_ (
    .A(_067_),
    .B(_094_),
    .Y(_001_[1])
  );
  NOR _135_ (
    .A(_069_),
    .B(_094_),
    .Y(_001_[2])
  );
  NOR _136_ (
    .A(_071_),
    .B(_094_),
    .Y(_001_[3])
  );
  NOR _137_ (
    .A(_073_),
    .B(_094_),
    .Y(_001_[4])
  );
  NOR _138_ (
    .A(_075_),
    .B(_094_),
    .Y(_001_[5])
  );
  NOR _139_ (
    .A(_077_),
    .B(_094_),
    .Y(_001_[6])
  );
  NOR _140_ (
    .A(_079_),
    .B(_094_),
    .Y(_001_[7])
  );
  NOR _141_ (
    .A(_080_),
    .B(_094_),
    .Y(_001_[8])
  );
  NOR _142_ (
    .A(_081_),
    .B(_094_),
    .Y(_001_[9])
  );
  NOR _143_ (
    .A(_082_),
    .B(_094_),
    .Y(_001_[10])
  );
  NOR _144_ (
    .A(_084_),
    .B(_094_),
    .Y(_001_[11])
  );
  NOR _145_ (
    .A(_070_),
    .B(data_in[3]),
    .Y(_096_)
  );
  NOR _146_ (
    .A(detector[3]),
    .B(_071_),
    .Y(_097_)
  );
  NOR _147_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _148_ (
    .A(detector[8]),
    .B(data_in[8]),
    .Y(_099_)
  );
  NOT _149_ (
    .A(_099_),
    .Y(_100_)
  );
  NAND _150_ (
    .A(detector[8]),
    .B(data_in[8]),
    .Y(_002_)
  );
  NAND _151_ (
    .A(_100_),
    .B(_002_),
    .Y(_003_)
  );
  NOR _152_ (
    .A(detector[9]),
    .B(data_in[9]),
    .Y(_004_)
  );
  NOT _153_ (
    .A(_004_),
    .Y(_005_)
  );
  NAND _154_ (
    .A(detector[9]),
    .B(data_in[9]),
    .Y(_006_)
  );
  NAND _155_ (
    .A(_005_),
    .B(_006_),
    .Y(_007_)
  );
  NOR _156_ (
    .A(detector[10]),
    .B(data_in[10]),
    .Y(_008_)
  );
  NAND _157_ (
    .A(detector[10]),
    .B(data_in[10]),
    .Y(_009_)
  );
  NOT _158_ (
    .A(_009_),
    .Y(_010_)
  );
  NOR _159_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _160_ (
    .A(_066_),
    .B(data_in[1]),
    .Y(_012_)
  );
  NOR _161_ (
    .A(detector[2]),
    .B(_069_),
    .Y(_013_)
  );
  NOR _162_ (
    .A(_064_),
    .B(data_in[0]),
    .Y(_014_)
  );
  NOR _163_ (
    .A(detector[1]),
    .B(_067_),
    .Y(_015_)
  );
  NOR _164_ (
    .A(_076_),
    .B(data_in[6]),
    .Y(_016_)
  );
  NOR _165_ (
    .A(detector[6]),
    .B(_077_),
    .Y(_017_)
  );
  NOR _166_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _167_ (
    .A(_068_),
    .B(data_in[2]),
    .Y(_019_)
  );
  NOR _168_ (
    .A(detector[5]),
    .B(_075_),
    .Y(_020_)
  );
  NOR _169_ (
    .A(_072_),
    .B(data_in[4]),
    .Y(_021_)
  );
  NOR _170_ (
    .A(detector[7]),
    .B(_079_),
    .Y(_022_)
  );
  NOR _171_ (
    .A(detector[4]),
    .B(_073_),
    .Y(_023_)
  );
  NOR _172_ (
    .A(_074_),
    .B(data_in[5]),
    .Y(_024_)
  );
  NOR _173_ (
    .A(detector[0]),
    .B(_065_),
    .Y(_025_)
  );
  NOR _174_ (
    .A(_083_),
    .B(data_in[11]),
    .Y(_026_)
  );
  NOR _175_ (
    .A(_078_),
    .B(data_in[7]),
    .Y(_027_)
  );
  NOR _176_ (
    .A(detector[11]),
    .B(_084_),
    .Y(_028_)
  );
  NOR _177_ (
    .A(_014_),
    .B(_025_),
    .Y(_029_)
  );
  NAND _178_ (
    .A(_007_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _179_ (
    .A(_011_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _180_ (
    .A(_012_),
    .B(_015_),
    .Y(_032_)
  );
  NOR _181_ (
    .A(_013_),
    .B(_019_),
    .Y(_033_)
  );
  NAND _182_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _183_ (
    .A(_026_),
    .B(_028_),
    .Y(_035_)
  );
  NAND _184_ (
    .A(_018_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _185_ (
    .A(_034_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _186_ (
    .A(_031_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _187_ (
    .A(_022_),
    .B(_027_),
    .Y(_039_)
  );
  NOR _188_ (
    .A(_021_),
    .B(_023_),
    .Y(_040_)
  );
  NAND _189_ (
    .A(_098_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _190_ (
    .A(_020_),
    .B(_024_),
    .Y(_042_)
  );
  NAND _191_ (
    .A(_003_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _192_ (
    .A(_041_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _193_ (
    .A(_039_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _194_ (
    .A(_038_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _195_ (
    .A(_085_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _196_ (
    .A(_085_),
    .B(_046_),
    .Y(_048_)
  );
  NAND _197_ (
    .A(_095_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _198_ (
    .A(_047_),
    .B(_049_),
    .Y(_000_[0])
  );
  NAND _199_ (
    .A(cuenta_est[1]),
    .B(_047_),
    .Y(_050_)
  );
  NOR _200_ (
    .A(cuenta_est[1]),
    .B(_047_),
    .Y(_051_)
  );
  NOR _201_ (
    .A(_094_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _202_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NOT _203_ (
    .A(_053_),
    .Y(_000_[1])
  );
  NOR _204_ (
    .A(_086_),
    .B(_050_),
    .Y(_054_)
  );
  NAND _205_ (
    .A(_086_),
    .B(_050_),
    .Y(_055_)
  );
  NAND _206_ (
    .A(_095_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _207_ (
    .A(_054_),
    .B(_056_),
    .Y(_000_[2])
  );
  NAND _208_ (
    .A(cuenta_est[3]),
    .B(_054_),
    .Y(_057_)
  );
  NOR _209_ (
    .A(cuenta_est[3]),
    .B(_054_),
    .Y(_058_)
  );
  NOR _210_ (
    .A(_094_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _211_ (
    .A(_057_),
    .B(_059_),
    .Y(_060_)
  );
  NOT _212_ (
    .A(_060_),
    .Y(_000_[3])
  );
  NOR _213_ (
    .A(_087_),
    .B(_057_),
    .Y(_061_)
  );
  NAND _214_ (
    .A(_087_),
    .B(_057_),
    .Y(_062_)
  );
  NAND _215_ (
    .A(_095_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _216_ (
    .A(_061_),
    .B(_063_),
    .Y(_000_[4])
  );
  (* src = "contador_est.v:10" *)
  DFF _217_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cuenta_est[0])
  );
  (* src = "contador_est.v:10" *)
  DFF _218_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cuenta_est[1])
  );
  (* src = "contador_est.v:10" *)
  DFF _219_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cuenta_est[2])
  );
  (* src = "contador_est.v:10" *)
  DFF _220_ (
    .C(clk),
    .D(_000_[3]),
    .Q(cuenta_est[3])
  );
  (* src = "contador_est.v:10" *)
  DFF _221_ (
    .C(clk),
    .D(_000_[4]),
    .Q(cuenta_est[4])
  );
  (* src = "contador_est.v:10" *)
  DFF _222_ (
    .C(clk),
    .D(_001_[0]),
    .Q(detector[0])
  );
  (* src = "contador_est.v:10" *)
  DFF _223_ (
    .C(clk),
    .D(_001_[1]),
    .Q(detector[1])
  );
  (* src = "contador_est.v:10" *)
  DFF _224_ (
    .C(clk),
    .D(_001_[2]),
    .Q(detector[2])
  );
  (* src = "contador_est.v:10" *)
  DFF _225_ (
    .C(clk),
    .D(_001_[3]),
    .Q(detector[3])
  );
  (* src = "contador_est.v:10" *)
  DFF _226_ (
    .C(clk),
    .D(_001_[4]),
    .Q(detector[4])
  );
  (* src = "contador_est.v:10" *)
  DFF _227_ (
    .C(clk),
    .D(_001_[5]),
    .Q(detector[5])
  );
  (* src = "contador_est.v:10" *)
  DFF _228_ (
    .C(clk),
    .D(_001_[6]),
    .Q(detector[6])
  );
  (* src = "contador_est.v:10" *)
  DFF _229_ (
    .C(clk),
    .D(_001_[7]),
    .Q(detector[7])
  );
  (* src = "contador_est.v:10" *)
  DFF _230_ (
    .C(clk),
    .D(_001_[8]),
    .Q(detector[8])
  );
  (* src = "contador_est.v:10" *)
  DFF _231_ (
    .C(clk),
    .D(_001_[9]),
    .Q(detector[9])
  );
  (* src = "contador_est.v:10" *)
  DFF _232_ (
    .C(clk),
    .D(_001_[10]),
    .Q(detector[10])
  );
  (* src = "contador_est.v:10" *)
  DFF _233_ (
    .C(clk),
    .D(_001_[11]),
    .Q(detector[11])
  );
endmodule
