/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador_est.v:1" *)
module contador_est(data_in, reset, clk, cuenta_est);
  (* src = "contador_est.v:10" *)
  wire [4:0] _000_;
  (* src = "contador_est.v:10" *)
  wire [11:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  (* src = "contador_est.v:4" *)
  input clk;
  (* src = "contador_est.v:5" *)
  output [4:0] cuenta_est;
  (* src = "contador_est.v:2" *)
  input [11:0] data_in;
  (* src = "contador_est.v:7" *)
  wire [11:0] detector;
  (* src = "contador_est.v:3" *)
  input reset;
  NOT _139_ (
    .A(reset),
    .Y(_087_)
  );
  NOT _140_ (
    .A(detector[1]),
    .Y(_088_)
  );
  NOT _141_ (
    .A(data_in[1]),
    .Y(_089_)
  );
  NOT _142_ (
    .A(detector[2]),
    .Y(_090_)
  );
  NOT _143_ (
    .A(data_in[2]),
    .Y(_091_)
  );
  NOT _144_ (
    .A(detector[5]),
    .Y(_092_)
  );
  NOT _145_ (
    .A(data_in[5]),
    .Y(_093_)
  );
  NOT _146_ (
    .A(detector[6]),
    .Y(_094_)
  );
  NOT _147_ (
    .A(data_in[6]),
    .Y(_095_)
  );
  NOT _148_ (
    .A(detector[11]),
    .Y(_096_)
  );
  NOT _149_ (
    .A(data_in[11]),
    .Y(_097_)
  );
  NOT _150_ (
    .A(cuenta_est[0]),
    .Y(_098_)
  );
  NOT _151_ (
    .A(cuenta_est[1]),
    .Y(_099_)
  );
  NOT _152_ (
    .A(cuenta_est[2]),
    .Y(_100_)
  );
  NOT _153_ (
    .A(cuenta_est[3]),
    .Y(_101_)
  );
  NAND _154_ (
    .A(detector[7]),
    .B(data_in[7]),
    .Y(_102_)
  );
  NOT _155_ (
    .A(_102_),
    .Y(_103_)
  );
  NOR _156_ (
    .A(detector[7]),
    .B(data_in[7]),
    .Y(_104_)
  );
  NOT _157_ (
    .A(_104_),
    .Y(_105_)
  );
  NAND _158_ (
    .A(_102_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _159_ (
    .A(_103_),
    .B(_104_),
    .Y(_107_)
  );
  NOR _160_ (
    .A(detector[10]),
    .B(data_in[10]),
    .Y(_108_)
  );
  NOT _161_ (
    .A(_108_),
    .Y(_109_)
  );
  NAND _162_ (
    .A(detector[10]),
    .B(data_in[10]),
    .Y(_110_)
  );
  NAND _163_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _164_ (
    .A(_106_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _165_ (
    .A(detector[9]),
    .B(data_in[9]),
    .Y(_113_)
  );
  NOT _166_ (
    .A(_113_),
    .Y(_114_)
  );
  NOR _167_ (
    .A(detector[9]),
    .B(data_in[9]),
    .Y(_115_)
  );
  NOT _168_ (
    .A(_115_),
    .Y(_116_)
  );
  NAND _169_ (
    .A(_113_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _170_ (
    .A(_114_),
    .B(_115_),
    .Y(_118_)
  );
  NAND _171_ (
    .A(detector[6]),
    .B(_095_),
    .Y(_119_)
  );
  NAND _172_ (
    .A(_094_),
    .B(data_in[6]),
    .Y(_120_)
  );
  NAND _173_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _174_ (
    .A(_092_),
    .B(data_in[5]),
    .Y(_122_)
  );
  NAND _175_ (
    .A(detector[5]),
    .B(_093_),
    .Y(_123_)
  );
  NOR _176_ (
    .A(detector[5]),
    .B(_093_),
    .Y(_124_)
  );
  NAND _177_ (
    .A(_092_),
    .B(data_in[5]),
    .Y(_125_)
  );
  NOR _178_ (
    .A(_122_),
    .B(_124_),
    .Y(_126_)
  );
  NAND _179_ (
    .A(_123_),
    .B(_125_),
    .Y(_127_)
  );
  NOR _180_ (
    .A(_096_),
    .B(data_in[11]),
    .Y(_128_)
  );
  NAND _181_ (
    .A(detector[11]),
    .B(_097_),
    .Y(_129_)
  );
  NOR _182_ (
    .A(detector[11]),
    .B(_097_),
    .Y(_130_)
  );
  NAND _183_ (
    .A(_096_),
    .B(data_in[11]),
    .Y(_131_)
  );
  NOR _184_ (
    .A(_128_),
    .B(_130_),
    .Y(_132_)
  );
  NAND _185_ (
    .A(_129_),
    .B(_131_),
    .Y(_133_)
  );
  NAND _186_ (
    .A(detector[3]),
    .B(data_in[3]),
    .Y(_134_)
  );
  NOT _187_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _188_ (
    .A(detector[3]),
    .B(data_in[3]),
    .Y(_136_)
  );
  NOT _189_ (
    .A(_136_),
    .Y(_137_)
  );
  NAND _190_ (
    .A(_134_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _191_ (
    .A(_135_),
    .B(_136_),
    .Y(_002_)
  );
  NOR _192_ (
    .A(_090_),
    .B(data_in[2]),
    .Y(_003_)
  );
  NAND _193_ (
    .A(detector[2]),
    .B(_091_),
    .Y(_004_)
  );
  NOR _194_ (
    .A(detector[2]),
    .B(_091_),
    .Y(_005_)
  );
  NAND _195_ (
    .A(_090_),
    .B(data_in[2]),
    .Y(_006_)
  );
  NOR _196_ (
    .A(_003_),
    .B(_005_),
    .Y(_007_)
  );
  NAND _197_ (
    .A(_004_),
    .B(_006_),
    .Y(_008_)
  );
  NAND _198_ (
    .A(detector[4]),
    .B(data_in[4]),
    .Y(_009_)
  );
  NOT _199_ (
    .A(_009_),
    .Y(_010_)
  );
  NOR _200_ (
    .A(detector[4]),
    .B(data_in[4]),
    .Y(_011_)
  );
  NOT _201_ (
    .A(_011_),
    .Y(_012_)
  );
  NAND _202_ (
    .A(_009_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _203_ (
    .A(_010_),
    .B(_011_),
    .Y(_014_)
  );
  NAND _204_ (
    .A(detector[0]),
    .B(data_in[0]),
    .Y(_015_)
  );
  NOT _205_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _206_ (
    .A(detector[0]),
    .B(data_in[0]),
    .Y(_017_)
  );
  NOT _207_ (
    .A(_017_),
    .Y(_018_)
  );
  NAND _208_ (
    .A(_015_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _209_ (
    .A(_016_),
    .B(_017_),
    .Y(_020_)
  );
  NOR _210_ (
    .A(_088_),
    .B(data_in[1]),
    .Y(_021_)
  );
  NAND _211_ (
    .A(detector[1]),
    .B(_089_),
    .Y(_022_)
  );
  NOR _212_ (
    .A(detector[1]),
    .B(_089_),
    .Y(_023_)
  );
  NAND _213_ (
    .A(_088_),
    .B(data_in[1]),
    .Y(_024_)
  );
  NOR _214_ (
    .A(_021_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _215_ (
    .A(_022_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _216_ (
    .A(detector[8]),
    .B(data_in[8]),
    .Y(_027_)
  );
  NOT _217_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _218_ (
    .A(detector[8]),
    .B(data_in[8]),
    .Y(_029_)
  );
  NOT _219_ (
    .A(_029_),
    .Y(_030_)
  );
  NAND _220_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _221_ (
    .A(_028_),
    .B(_029_),
    .Y(_032_)
  );
  NOR _222_ (
    .A(_008_),
    .B(_026_),
    .Y(_033_)
  );
  NAND _223_ (
    .A(_007_),
    .B(_025_),
    .Y(_034_)
  );
  NOR _224_ (
    .A(_121_),
    .B(_133_),
    .Y(_035_)
  );
  NAND _225_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _226_ (
    .A(_002_),
    .B(_014_),
    .Y(_037_)
  );
  NAND _227_ (
    .A(_138_),
    .B(_013_),
    .Y(_038_)
  );
  NOR _228_ (
    .A(_127_),
    .B(_032_),
    .Y(_039_)
  );
  NAND _229_ (
    .A(_126_),
    .B(_031_),
    .Y(_040_)
  );
  NAND _230_ (
    .A(_037_),
    .B(_039_),
    .Y(_041_)
  );
  NOR _231_ (
    .A(_036_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _232_ (
    .A(_117_),
    .B(_019_),
    .Y(_043_)
  );
  NOR _233_ (
    .A(_112_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _234_ (
    .A(_118_),
    .B(_038_),
    .Y(_045_)
  );
  NOR _235_ (
    .A(_020_),
    .B(_034_),
    .Y(_046_)
  );
  NAND _236_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _237_ (
    .A(_107_),
    .B(_121_),
    .Y(_048_)
  );
  NAND _238_ (
    .A(_111_),
    .B(_132_),
    .Y(_049_)
  );
  NOR _239_ (
    .A(_040_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _240_ (
    .A(_048_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _241_ (
    .A(_047_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _242_ (
    .A(_042_),
    .B(_044_),
    .Y(_053_)
  );
  NOR _243_ (
    .A(_098_),
    .B(_052_),
    .Y(_054_)
  );
  NAND _244_ (
    .A(cuenta_est[0]),
    .B(_053_),
    .Y(_055_)
  );
  NAND _245_ (
    .A(_098_),
    .B(_052_),
    .Y(_056_)
  );
  NAND _246_ (
    .A(reset),
    .B(_056_),
    .Y(_057_)
  );
  NOR _247_ (
    .A(_054_),
    .B(_057_),
    .Y(_000_[0])
  );
  NOR _248_ (
    .A(_099_),
    .B(_055_),
    .Y(_058_)
  );
  NAND _249_ (
    .A(cuenta_est[1]),
    .B(_054_),
    .Y(_059_)
  );
  NOR _250_ (
    .A(cuenta_est[1]),
    .B(_054_),
    .Y(_060_)
  );
  NOR _251_ (
    .A(_087_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _252_ (
    .A(_059_),
    .B(_061_),
    .Y(_062_)
  );
  NOT _253_ (
    .A(_062_),
    .Y(_000_[1])
  );
  NOR _254_ (
    .A(_100_),
    .B(_059_),
    .Y(_063_)
  );
  NAND _255_ (
    .A(cuenta_est[2]),
    .B(_058_),
    .Y(_064_)
  );
  NAND _256_ (
    .A(_100_),
    .B(_059_),
    .Y(_065_)
  );
  NAND _257_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  NOR _258_ (
    .A(_063_),
    .B(_066_),
    .Y(_000_[2])
  );
  NOR _259_ (
    .A(_101_),
    .B(_064_),
    .Y(_067_)
  );
  NAND _260_ (
    .A(cuenta_est[3]),
    .B(_063_),
    .Y(_068_)
  );
  NOR _261_ (
    .A(cuenta_est[3]),
    .B(_063_),
    .Y(_069_)
  );
  NOR _262_ (
    .A(_087_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _263_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NOT _264_ (
    .A(_071_),
    .Y(_000_[3])
  );
  NOR _265_ (
    .A(cuenta_est[4]),
    .B(_067_),
    .Y(_072_)
  );
  NAND _266_ (
    .A(cuenta_est[4]),
    .B(_067_),
    .Y(_073_)
  );
  NAND _267_ (
    .A(reset),
    .B(_073_),
    .Y(_074_)
  );
  NOR _268_ (
    .A(_072_),
    .B(_074_),
    .Y(_000_[4])
  );
  NAND _269_ (
    .A(reset),
    .B(data_in[0]),
    .Y(_075_)
  );
  NOT _270_ (
    .A(_075_),
    .Y(_001_[0])
  );
  NAND _271_ (
    .A(reset),
    .B(data_in[1]),
    .Y(_076_)
  );
  NOT _272_ (
    .A(_076_),
    .Y(_001_[1])
  );
  NAND _273_ (
    .A(reset),
    .B(data_in[2]),
    .Y(_077_)
  );
  NOT _274_ (
    .A(_077_),
    .Y(_001_[2])
  );
  NAND _275_ (
    .A(reset),
    .B(data_in[3]),
    .Y(_078_)
  );
  NOT _276_ (
    .A(_078_),
    .Y(_001_[3])
  );
  NAND _277_ (
    .A(reset),
    .B(data_in[4]),
    .Y(_079_)
  );
  NOT _278_ (
    .A(_079_),
    .Y(_001_[4])
  );
  NAND _279_ (
    .A(reset),
    .B(data_in[5]),
    .Y(_080_)
  );
  NOT _280_ (
    .A(_080_),
    .Y(_001_[5])
  );
  NAND _281_ (
    .A(reset),
    .B(data_in[6]),
    .Y(_081_)
  );
  NOT _282_ (
    .A(_081_),
    .Y(_001_[6])
  );
  NAND _283_ (
    .A(reset),
    .B(data_in[7]),
    .Y(_082_)
  );
  NOT _284_ (
    .A(_082_),
    .Y(_001_[7])
  );
  NAND _285_ (
    .A(reset),
    .B(data_in[8]),
    .Y(_083_)
  );
  NOT _286_ (
    .A(_083_),
    .Y(_001_[8])
  );
  NAND _287_ (
    .A(reset),
    .B(data_in[9]),
    .Y(_084_)
  );
  NOT _288_ (
    .A(_084_),
    .Y(_001_[9])
  );
  NAND _289_ (
    .A(reset),
    .B(data_in[10]),
    .Y(_085_)
  );
  NOT _290_ (
    .A(_085_),
    .Y(_001_[10])
  );
  NAND _291_ (
    .A(reset),
    .B(data_in[11]),
    .Y(_086_)
  );
  NOT _292_ (
    .A(_086_),
    .Y(_001_[11])
  );
  (* src = "contador_est.v:10" *)
  DFF _293_ (
    .C(clk),
    .D(_001_[0]),
    .Q(detector[0])
  );
  (* src = "contador_est.v:10" *)
  DFF _294_ (
    .C(clk),
    .D(_001_[1]),
    .Q(detector[1])
  );
  (* src = "contador_est.v:10" *)
  DFF _295_ (
    .C(clk),
    .D(_001_[2]),
    .Q(detector[2])
  );
  (* src = "contador_est.v:10" *)
  DFF _296_ (
    .C(clk),
    .D(_001_[3]),
    .Q(detector[3])
  );
  (* src = "contador_est.v:10" *)
  DFF _297_ (
    .C(clk),
    .D(_001_[4]),
    .Q(detector[4])
  );
  (* src = "contador_est.v:10" *)
  DFF _298_ (
    .C(clk),
    .D(_001_[5]),
    .Q(detector[5])
  );
  (* src = "contador_est.v:10" *)
  DFF _299_ (
    .C(clk),
    .D(_001_[6]),
    .Q(detector[6])
  );
  (* src = "contador_est.v:10" *)
  DFF _300_ (
    .C(clk),
    .D(_001_[7]),
    .Q(detector[7])
  );
  (* src = "contador_est.v:10" *)
  DFF _301_ (
    .C(clk),
    .D(_001_[8]),
    .Q(detector[8])
  );
  (* src = "contador_est.v:10" *)
  DFF _302_ (
    .C(clk),
    .D(_001_[9]),
    .Q(detector[9])
  );
  (* src = "contador_est.v:10" *)
  DFF _303_ (
    .C(clk),
    .D(_001_[10]),
    .Q(detector[10])
  );
  (* src = "contador_est.v:10" *)
  DFF _304_ (
    .C(clk),
    .D(_001_[11]),
    .Q(detector[11])
  );
  (* src = "contador_est.v:10" *)
  DFF _305_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cuenta_est[0])
  );
  (* src = "contador_est.v:10" *)
  DFF _306_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cuenta_est[1])
  );
  (* src = "contador_est.v:10" *)
  DFF _307_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cuenta_est[2])
  );
  (* src = "contador_est.v:10" *)
  DFF _308_ (
    .C(clk),
    .D(_000_[3]),
    .Q(cuenta_est[3])
  );
  (* src = "contador_est.v:10" *)
  DFF _309_ (
    .C(clk),
    .D(_000_[4]),
    .Q(cuenta_est[4])
  );
endmodule
