/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "referee_1_est.v:4" *)
module referee_1_est(push_0, push_1, push_2, push_3, pop_0, pop_1, pop_2, pop_3, almost_full_0, almost_full_1, almost_full_2, almost_full_3, empty_0, empty_1, empty_2, empty_3, clk, reset);
  (* src = "referee_1_est.v:17" *)
  wire _000_;
  (* src = "referee_1_est.v:17" *)
  wire _001_;
  (* src = "referee_1_est.v:17" *)
  wire _002_;
  (* src = "referee_1_est.v:17" *)
  wire _003_;
  (* src = "referee_1_est.v:17" *)
  wire _004_;
  (* src = "referee_1_est.v:17" *)
  wire _005_;
  (* src = "referee_1_est.v:17" *)
  wire _006_;
  (* src = "referee_1_est.v:17" *)
  wire _007_;
  (* src = "referee_1_est.v:17" *)
  wire [1:0] _008_;
  (* src = "referee_1_est.v:17" *)
  wire [3:0] _009_;
  (* src = "referee_1_est.v:17" *)
  wire [3:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  (* src = "referee_1_est.v:9" *)
  input almost_full_0;
  (* src = "referee_1_est.v:9" *)
  input almost_full_1;
  (* src = "referee_1_est.v:9" *)
  input almost_full_2;
  (* src = "referee_1_est.v:9" *)
  input almost_full_3;
  (* src = "referee_1_est.v:11" *)
  input clk;
  (* src = "referee_1_est.v:10" *)
  input empty_0;
  (* src = "referee_1_est.v:10" *)
  input empty_1;
  (* src = "referee_1_est.v:10" *)
  input empty_2;
  (* src = "referee_1_est.v:10" *)
  input empty_3;
  (* src = "referee_1_est.v:6" *)
  output pop_0;
  (* src = "referee_1_est.v:6" *)
  output pop_1;
  (* src = "referee_1_est.v:6" *)
  output pop_2;
  (* src = "referee_1_est.v:6" *)
  output pop_3;
  (* src = "referee_1_est.v:5" *)
  output push_0;
  (* src = "referee_1_est.v:5" *)
  output push_1;
  (* src = "referee_1_est.v:5" *)
  output push_2;
  (* src = "referee_1_est.v:5" *)
  output push_3;
  (* src = "referee_1_est.v:15" *)
  wire [1:0] push_toggle;
  (* src = "referee_1_est.v:11" *)
  input reset;
  (* src = "referee_1_est.v:13" *)
  wire [3:0] rr_pop_toggle;
  (* src = "referee_1_est.v:14" *)
  wire [3:0] wrr_pop_toggle;
  NOT _232_ (
    .A(wrr_pop_toggle[2]),
    .Y(_180_)
  );
  NOT _233_ (
    .A(push_toggle[1]),
    .Y(_181_)
  );
  NOT _234_ (
    .A(push_toggle[0]),
    .Y(_182_)
  );
  NOT _235_ (
    .A(rr_pop_toggle[1]),
    .Y(_183_)
  );
  NOT _236_ (
    .A(rr_pop_toggle[0]),
    .Y(_184_)
  );
  NOT _237_ (
    .A(rr_pop_toggle[3]),
    .Y(_185_)
  );
  NOT _238_ (
    .A(reset),
    .Y(_186_)
  );
  NOT _239_ (
    .A(wrr_pop_toggle[0]),
    .Y(_187_)
  );
  NOT _240_ (
    .A(wrr_pop_toggle[1]),
    .Y(_188_)
  );
  NOT _241_ (
    .A(wrr_pop_toggle[3]),
    .Y(_189_)
  );
  NOT _242_ (
    .A(pop_3),
    .Y(_190_)
  );
  NOT _243_ (
    .A(empty_3),
    .Y(_191_)
  );
  NOT _244_ (
    .A(pop_2),
    .Y(_192_)
  );
  NOT _245_ (
    .A(empty_2),
    .Y(_193_)
  );
  NOT _246_ (
    .A(pop_1),
    .Y(_194_)
  );
  NOT _247_ (
    .A(empty_1),
    .Y(_195_)
  );
  NOT _248_ (
    .A(pop_0),
    .Y(_196_)
  );
  NOT _249_ (
    .A(empty_0),
    .Y(_197_)
  );
  NOT _250_ (
    .A(push_3),
    .Y(_198_)
  );
  NOT _251_ (
    .A(push_2),
    .Y(_199_)
  );
  NOR _252_ (
    .A(almost_full_0),
    .B(almost_full_1),
    .Y(_200_)
  );
  NOT _253_ (
    .A(_200_),
    .Y(_201_)
  );
  NOR _254_ (
    .A(almost_full_2),
    .B(almost_full_3),
    .Y(_202_)
  );
  NOT _255_ (
    .A(_202_),
    .Y(_203_)
  );
  NOR _256_ (
    .A(_201_),
    .B(_203_),
    .Y(_204_)
  );
  NAND _257_ (
    .A(_200_),
    .B(_202_),
    .Y(_205_)
  );
  NOR _258_ (
    .A(_182_),
    .B(_205_),
    .Y(_206_)
  );
  NAND _259_ (
    .A(_182_),
    .B(_205_),
    .Y(_207_)
  );
  NAND _260_ (
    .A(reset),
    .B(_207_),
    .Y(_208_)
  );
  NOR _261_ (
    .A(_206_),
    .B(_208_),
    .Y(_008_[0])
  );
  NOR _262_ (
    .A(push_toggle[1]),
    .B(_206_),
    .Y(_209_)
  );
  NAND _263_ (
    .A(reset),
    .B(_205_),
    .Y(_210_)
  );
  NOT _264_ (
    .A(_210_),
    .Y(_211_)
  );
  NAND _265_ (
    .A(push_toggle[1]),
    .B(push_toggle[0]),
    .Y(_212_)
  );
  NOT _266_ (
    .A(_212_),
    .Y(_213_)
  );
  NAND _267_ (
    .A(_204_),
    .B(_213_),
    .Y(_214_)
  );
  NAND _268_ (
    .A(reset),
    .B(_214_),
    .Y(_215_)
  );
  NOR _269_ (
    .A(_209_),
    .B(_215_),
    .Y(_008_[1])
  );
  NOR _270_ (
    .A(wrr_pop_toggle[2]),
    .B(wrr_pop_toggle[1]),
    .Y(_216_)
  );
  NOR _271_ (
    .A(wrr_pop_toggle[2]),
    .B(_189_),
    .Y(_217_)
  );
  NAND _272_ (
    .A(_180_),
    .B(wrr_pop_toggle[3]),
    .Y(_218_)
  );
  NAND _273_ (
    .A(wrr_pop_toggle[3]),
    .B(_216_),
    .Y(_219_)
  );
  NOR _274_ (
    .A(_180_),
    .B(wrr_pop_toggle[3]),
    .Y(_220_)
  );
  NAND _275_ (
    .A(wrr_pop_toggle[2]),
    .B(_189_),
    .Y(_221_)
  );
  NOR _276_ (
    .A(_187_),
    .B(_188_),
    .Y(_222_)
  );
  NAND _277_ (
    .A(wrr_pop_toggle[0]),
    .B(wrr_pop_toggle[1]),
    .Y(_223_)
  );
  NOR _278_ (
    .A(_221_),
    .B(_223_),
    .Y(_224_)
  );
  NAND _279_ (
    .A(_220_),
    .B(_222_),
    .Y(_225_)
  );
  NAND _280_ (
    .A(_219_),
    .B(_225_),
    .Y(_226_)
  );
  NOR _281_ (
    .A(wrr_pop_toggle[0]),
    .B(wrr_pop_toggle[1]),
    .Y(_227_)
  );
  NAND _282_ (
    .A(_187_),
    .B(_188_),
    .Y(_228_)
  );
  NOR _283_ (
    .A(_218_),
    .B(_228_),
    .Y(_229_)
  );
  NAND _284_ (
    .A(_217_),
    .B(_227_),
    .Y(_230_)
  );
  NAND _285_ (
    .A(_225_),
    .B(_230_),
    .Y(_231_)
  );
  NOR _286_ (
    .A(_224_),
    .B(_229_),
    .Y(_011_)
  );
  NOR _287_ (
    .A(empty_2),
    .B(_011_),
    .Y(_012_)
  );
  NAND _288_ (
    .A(_193_),
    .B(_231_),
    .Y(_013_)
  );
  NOR _289_ (
    .A(pop_2),
    .B(_013_),
    .Y(_014_)
  );
  NOR _290_ (
    .A(_187_),
    .B(_219_),
    .Y(_015_)
  );
  NOR _291_ (
    .A(_190_),
    .B(empty_3),
    .Y(_016_)
  );
  NOT _292_ (
    .A(_016_),
    .Y(_017_)
  );
  NAND _293_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _294_ (
    .A(_221_),
    .B(_222_),
    .Y(_019_)
  );
  NAND _295_ (
    .A(_220_),
    .B(_223_),
    .Y(_020_)
  );
  NOR _296_ (
    .A(wrr_pop_toggle[2]),
    .B(wrr_pop_toggle[3]),
    .Y(_021_)
  );
  NAND _297_ (
    .A(_180_),
    .B(_189_),
    .Y(_022_)
  );
  NOR _298_ (
    .A(wrr_pop_toggle[3]),
    .B(_224_),
    .Y(_023_)
  );
  NOT _299_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _300_ (
    .A(_192_),
    .B(empty_2),
    .Y(_025_)
  );
  NAND _301_ (
    .A(wrr_pop_toggle[0]),
    .B(_018_),
    .Y(_026_)
  );
  NOR _302_ (
    .A(_014_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _303_ (
    .A(_015_),
    .B(_016_),
    .Y(_028_)
  );
  NAND _304_ (
    .A(_011_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _305_ (
    .A(_231_),
    .B(_025_),
    .Y(_030_)
  );
  NAND _306_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _307_ (
    .A(wrr_pop_toggle[0]),
    .B(_031_),
    .Y(_032_)
  );
  NOR _308_ (
    .A(_027_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _309_ (
    .A(_023_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _310_ (
    .A(pop_1),
    .B(_195_),
    .Y(_035_)
  );
  NOR _311_ (
    .A(pop_1),
    .B(empty_1),
    .Y(_036_)
  );
  NAND _312_ (
    .A(wrr_pop_toggle[0]),
    .B(_036_),
    .Y(_037_)
  );
  NOR _313_ (
    .A(wrr_pop_toggle[0]),
    .B(_035_),
    .Y(_038_)
  );
  NOR _314_ (
    .A(_020_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _315_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _316_ (
    .A(empty_0),
    .B(_022_),
    .Y(_041_)
  );
  NAND _317_ (
    .A(_197_),
    .B(_021_),
    .Y(_042_)
  );
  NAND _318_ (
    .A(wrr_pop_toggle[0]),
    .B(_196_),
    .Y(_043_)
  );
  NAND _319_ (
    .A(_187_),
    .B(pop_0),
    .Y(_044_)
  );
  NAND _320_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _321_ (
    .A(_042_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _322_ (
    .A(_204_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _323_ (
    .A(_040_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _324_ (
    .A(_034_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _325_ (
    .A(wrr_pop_toggle[0]),
    .B(_205_),
    .Y(_050_)
  );
  NOT _326_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND _327_ (
    .A(reset),
    .B(_051_),
    .Y(_052_)
  );
  NOR _328_ (
    .A(_049_),
    .B(_052_),
    .Y(_010_[0])
  );
  NOR _329_ (
    .A(_222_),
    .B(_227_),
    .Y(_053_)
  );
  NAND _330_ (
    .A(_223_),
    .B(_228_),
    .Y(_054_)
  );
  NAND _331_ (
    .A(_192_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _332_ (
    .A(wrr_pop_toggle[1]),
    .B(pop_2),
    .Y(_056_)
  );
  NAND _333_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _334_ (
    .A(_012_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _335_ (
    .A(wrr_pop_toggle[1]),
    .B(_221_),
    .Y(_059_)
  );
  NAND _336_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _337_ (
    .A(_024_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _338_ (
    .A(_036_),
    .B(_054_),
    .Y(_062_)
  );
  NOR _339_ (
    .A(wrr_pop_toggle[1]),
    .B(_035_),
    .Y(_063_)
  );
  NAND _340_ (
    .A(_019_),
    .B(_035_),
    .Y(_064_)
  );
  NOR _341_ (
    .A(_020_),
    .B(_063_),
    .Y(_065_)
  );
  NAND _342_ (
    .A(_062_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _343_ (
    .A(_196_),
    .B(_054_),
    .Y(_067_)
  );
  NOR _344_ (
    .A(wrr_pop_toggle[1]),
    .B(_196_),
    .Y(_068_)
  );
  NOR _345_ (
    .A(_042_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _346_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _347_ (
    .A(_066_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _348_ (
    .A(_204_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _349_ (
    .A(_061_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _350_ (
    .A(wrr_pop_toggle[1]),
    .B(_205_),
    .Y(_074_)
  );
  NAND _351_ (
    .A(reset),
    .B(_073_),
    .Y(_075_)
  );
  NOR _352_ (
    .A(_074_),
    .B(_075_),
    .Y(_010_[1])
  );
  NOR _353_ (
    .A(empty_0),
    .B(_222_),
    .Y(_076_)
  );
  NAND _354_ (
    .A(pop_0),
    .B(_197_),
    .Y(_077_)
  );
  NAND _355_ (
    .A(_021_),
    .B(_077_),
    .Y(_078_)
  );
  NOT _356_ (
    .A(_078_),
    .Y(_079_)
  );
  NOR _357_ (
    .A(_076_),
    .B(_078_),
    .Y(_080_)
  );
  NOT _358_ (
    .A(_080_),
    .Y(_081_)
  );
  NAND _359_ (
    .A(_058_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _360_ (
    .A(_205_),
    .B(_231_),
    .Y(_083_)
  );
  NAND _361_ (
    .A(wrr_pop_toggle[2]),
    .B(_083_),
    .Y(_084_)
  );
  NAND _362_ (
    .A(_205_),
    .B(_082_),
    .Y(_085_)
  );
  NAND _363_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _364_ (
    .A(reset),
    .B(_086_),
    .Y(_087_)
  );
  NOT _365_ (
    .A(_087_),
    .Y(_010_[2])
  );
  NAND _366_ (
    .A(_211_),
    .B(_018_),
    .Y(_088_)
  );
  NOR _367_ (
    .A(_023_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _368_ (
    .A(_058_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _369_ (
    .A(_186_),
    .B(_205_),
    .Y(_091_)
  );
  NAND _370_ (
    .A(reset),
    .B(_204_),
    .Y(_092_)
  );
  NAND _371_ (
    .A(wrr_pop_toggle[3]),
    .B(_091_),
    .Y(_093_)
  );
  NAND _372_ (
    .A(_090_),
    .B(_093_),
    .Y(_010_[3])
  );
  NOR _373_ (
    .A(rr_pop_toggle[2]),
    .B(rr_pop_toggle[3]),
    .Y(_094_)
  );
  NAND _374_ (
    .A(rr_pop_toggle[0]),
    .B(_094_),
    .Y(_095_)
  );
  NOR _375_ (
    .A(rr_pop_toggle[0]),
    .B(_094_),
    .Y(_096_)
  );
  NOT _376_ (
    .A(_096_),
    .Y(_097_)
  );
  NAND _377_ (
    .A(_095_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _378_ (
    .A(_092_),
    .B(_098_),
    .Y(_009_[0])
  );
  NAND _379_ (
    .A(rr_pop_toggle[1]),
    .B(_094_),
    .Y(_099_)
  );
  NOT _380_ (
    .A(_099_),
    .Y(_100_)
  );
  NOR _381_ (
    .A(_183_),
    .B(_095_),
    .Y(_101_)
  );
  NAND _382_ (
    .A(_183_),
    .B(_095_),
    .Y(_102_)
  );
  NAND _383_ (
    .A(_091_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _384_ (
    .A(_101_),
    .B(_103_),
    .Y(_009_[1])
  );
  NAND _385_ (
    .A(_212_),
    .B(_101_),
    .Y(_104_)
  );
  NOT _386_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _387_ (
    .A(rr_pop_toggle[2]),
    .B(_105_),
    .Y(_106_)
  );
  NOR _388_ (
    .A(_092_),
    .B(_106_),
    .Y(_009_[2])
  );
  NOR _389_ (
    .A(_185_),
    .B(_092_),
    .Y(_009_[3])
  );
  NOR _390_ (
    .A(push_toggle[1]),
    .B(push_toggle[0]),
    .Y(_107_)
  );
  NOR _391_ (
    .A(_198_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _392_ (
    .A(_213_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _393_ (
    .A(_092_),
    .B(_109_),
    .Y(_007_)
  );
  NOR _394_ (
    .A(_181_),
    .B(push_toggle[0]),
    .Y(_110_)
  );
  NAND _395_ (
    .A(push_toggle[1]),
    .B(_182_),
    .Y(_111_)
  );
  NOR _396_ (
    .A(push_toggle[1]),
    .B(_199_),
    .Y(_112_)
  );
  NOR _397_ (
    .A(_110_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _398_ (
    .A(_092_),
    .B(_113_),
    .Y(_006_)
  );
  NOR _399_ (
    .A(push_toggle[1]),
    .B(_182_),
    .Y(_114_)
  );
  NOR _400_ (
    .A(push_1),
    .B(_114_),
    .Y(_115_)
  );
  NAND _401_ (
    .A(_091_),
    .B(_111_),
    .Y(_116_)
  );
  NOR _402_ (
    .A(_115_),
    .B(_116_),
    .Y(_005_)
  );
  NAND _403_ (
    .A(_183_),
    .B(_094_),
    .Y(_117_)
  );
  NOR _404_ (
    .A(rr_pop_toggle[1]),
    .B(_095_),
    .Y(_118_)
  );
  NAND _405_ (
    .A(empty_1),
    .B(_118_),
    .Y(_119_)
  );
  NAND _406_ (
    .A(_184_),
    .B(_100_),
    .Y(_120_)
  );
  NAND _407_ (
    .A(reset),
    .B(_120_),
    .Y(_121_)
  );
  NOR _408_ (
    .A(pop_1),
    .B(_118_),
    .Y(_122_)
  );
  NOR _409_ (
    .A(_121_),
    .B(_122_),
    .Y(_123_)
  );
  NAND _410_ (
    .A(_119_),
    .B(_123_),
    .Y(_124_)
  );
  NAND _411_ (
    .A(_210_),
    .B(_124_),
    .Y(_125_)
  );
  NOT _412_ (
    .A(_125_),
    .Y(_126_)
  );
  NAND _413_ (
    .A(_226_),
    .B(_016_),
    .Y(_127_)
  );
  NOR _414_ (
    .A(_231_),
    .B(_023_),
    .Y(_128_)
  );
  NOR _415_ (
    .A(_023_),
    .B(_029_),
    .Y(_129_)
  );
  NAND _416_ (
    .A(_127_),
    .B(_128_),
    .Y(_130_)
  );
  NOR _417_ (
    .A(_079_),
    .B(_129_),
    .Y(_131_)
  );
  NOR _418_ (
    .A(_194_),
    .B(_131_),
    .Y(_132_)
  );
  NAND _419_ (
    .A(_019_),
    .B(_036_),
    .Y(_133_)
  );
  NAND _420_ (
    .A(_205_),
    .B(_133_),
    .Y(_134_)
  );
  NOR _421_ (
    .A(_132_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _422_ (
    .A(_126_),
    .B(_135_),
    .Y(_001_)
  );
  NOR _423_ (
    .A(_011_),
    .B(_025_),
    .Y(_136_)
  );
  NAND _424_ (
    .A(pop_0),
    .B(_130_),
    .Y(_137_)
  );
  NOR _425_ (
    .A(_136_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _426_ (
    .A(pop_0),
    .B(_041_),
    .Y(_139_)
  );
  NOR _427_ (
    .A(_138_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _428_ (
    .A(_204_),
    .B(_140_),
    .Y(_141_)
  );
  NOR _429_ (
    .A(rr_pop_toggle[0]),
    .B(_117_),
    .Y(_142_)
  );
  NOT _430_ (
    .A(_142_),
    .Y(_143_)
  );
  NOR _431_ (
    .A(empty_0),
    .B(_143_),
    .Y(_144_)
  );
  NAND _432_ (
    .A(pop_0),
    .B(_117_),
    .Y(_145_)
  );
  NOR _433_ (
    .A(_205_),
    .B(_144_),
    .Y(_146_)
  );
  NAND _434_ (
    .A(_145_),
    .B(_146_),
    .Y(_147_)
  );
  NAND _435_ (
    .A(reset),
    .B(_147_),
    .Y(_148_)
  );
  NOR _436_ (
    .A(_141_),
    .B(_148_),
    .Y(_000_)
  );
  NAND _437_ (
    .A(push_toggle[1]),
    .B(push_0),
    .Y(_149_)
  );
  NOT _438_ (
    .A(_149_),
    .Y(_150_)
  );
  NOR _439_ (
    .A(_107_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _440_ (
    .A(_092_),
    .B(_151_),
    .Y(_004_)
  );
  NOR _441_ (
    .A(_190_),
    .B(_064_),
    .Y(_152_)
  );
  NAND _442_ (
    .A(pop_3),
    .B(_226_),
    .Y(_153_)
  );
  NOR _443_ (
    .A(_136_),
    .B(_153_),
    .Y(_154_)
  );
  NAND _444_ (
    .A(_191_),
    .B(_015_),
    .Y(_155_)
  );
  NAND _445_ (
    .A(_190_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _446_ (
    .A(_020_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _447_ (
    .A(_154_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _448_ (
    .A(_152_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _449_ (
    .A(_205_),
    .B(_022_),
    .Y(_160_)
  );
  NOR _450_ (
    .A(_159_),
    .B(_160_),
    .Y(_161_)
  );
  NOR _451_ (
    .A(pop_3),
    .B(_101_),
    .Y(_162_)
  );
  NAND _452_ (
    .A(empty_3),
    .B(_101_),
    .Y(_163_)
  );
  NOR _453_ (
    .A(_205_),
    .B(_142_),
    .Y(_164_)
  );
  NAND _454_ (
    .A(_163_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _455_ (
    .A(_162_),
    .B(_165_),
    .Y(_166_)
  );
  NOR _456_ (
    .A(_161_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _457_ (
    .A(_186_),
    .B(_167_),
    .Y(_003_)
  );
  NAND _458_ (
    .A(_219_),
    .B(_221_),
    .Y(_168_)
  );
  NAND _459_ (
    .A(_064_),
    .B(_168_),
    .Y(_169_)
  );
  NAND _460_ (
    .A(_022_),
    .B(_169_),
    .Y(_170_)
  );
  NAND _461_ (
    .A(_078_),
    .B(_170_),
    .Y(_171_)
  );
  NAND _462_ (
    .A(pop_2),
    .B(_171_),
    .Y(_172_)
  );
  NAND _463_ (
    .A(_205_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _464_ (
    .A(_014_),
    .B(_173_),
    .Y(_174_)
  );
  NOR _465_ (
    .A(empty_2),
    .B(_120_),
    .Y(_175_)
  );
  NAND _466_ (
    .A(pop_2),
    .B(_099_),
    .Y(_176_)
  );
  NOR _467_ (
    .A(_205_),
    .B(_175_),
    .Y(_177_)
  );
  NAND _468_ (
    .A(_176_),
    .B(_177_),
    .Y(_178_)
  );
  NAND _469_ (
    .A(reset),
    .B(_178_),
    .Y(_179_)
  );
  NOR _470_ (
    .A(_174_),
    .B(_179_),
    .Y(_002_)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _471_ (
    .C(clk),
    .D(_002_),
    .Q(pop_2)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _472_ (
    .C(clk),
    .D(_003_),
    .Q(pop_3)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _473_ (
    .C(clk),
    .D(_004_),
    .Q(push_0)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _474_ (
    .C(clk),
    .D(_000_),
    .Q(pop_0)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _475_ (
    .C(clk),
    .D(_001_),
    .Q(pop_1)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _476_ (
    .C(clk),
    .D(_005_),
    .Q(push_1)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _477_ (
    .C(clk),
    .D(_006_),
    .Q(push_2)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _478_ (
    .C(clk),
    .D(_007_),
    .Q(push_3)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _479_ (
    .C(clk),
    .D(_009_[0]),
    .Q(rr_pop_toggle[0])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _480_ (
    .C(clk),
    .D(_009_[1]),
    .Q(rr_pop_toggle[1])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _481_ (
    .C(clk),
    .D(_009_[2]),
    .Q(rr_pop_toggle[2])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _482_ (
    .C(clk),
    .D(_009_[3]),
    .Q(rr_pop_toggle[3])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _483_ (
    .C(clk),
    .D(_010_[0]),
    .Q(wrr_pop_toggle[0])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _484_ (
    .C(clk),
    .D(_010_[1]),
    .Q(wrr_pop_toggle[1])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _485_ (
    .C(clk),
    .D(_010_[2]),
    .Q(wrr_pop_toggle[2])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _486_ (
    .C(clk),
    .D(_010_[3]),
    .Q(wrr_pop_toggle[3])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _487_ (
    .C(clk),
    .D(_008_[0]),
    .Q(push_toggle[0])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _488_ (
    .C(clk),
    .D(_008_[1]),
    .Q(push_toggle[1])
  );
endmodule
