/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "referee_1_est.v:4" *)
module referee_1_est(push_0, push_1, push_2, push_3, pop_0, pop_1, pop_2, pop_3, almost_full_0, almost_full_1, almost_full_2, almost_full_3, empty_0, empty_1, empty_2, empty_3, clk, reset);
  (* src = "referee_1_est.v:17" *)
  wire _000_;
  (* src = "referee_1_est.v:17" *)
  wire _001_;
  (* src = "referee_1_est.v:17" *)
  wire _002_;
  (* src = "referee_1_est.v:17" *)
  wire _003_;
  (* src = "referee_1_est.v:17" *)
  wire _004_;
  (* src = "referee_1_est.v:17" *)
  wire _005_;
  (* src = "referee_1_est.v:17" *)
  wire _006_;
  (* src = "referee_1_est.v:17" *)
  wire _007_;
  (* src = "referee_1_est.v:17" *)
  wire [1:0] _008_;
  (* src = "referee_1_est.v:17" *)
  wire [3:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  (* src = "referee_1_est.v:9" *)
  input almost_full_0;
  (* src = "referee_1_est.v:9" *)
  input almost_full_1;
  (* src = "referee_1_est.v:9" *)
  input almost_full_2;
  (* src = "referee_1_est.v:9" *)
  input almost_full_3;
  (* src = "referee_1_est.v:11" *)
  input clk;
  (* src = "referee_1_est.v:10" *)
  input empty_0;
  (* src = "referee_1_est.v:10" *)
  input empty_1;
  (* src = "referee_1_est.v:10" *)
  input empty_2;
  (* src = "referee_1_est.v:10" *)
  input empty_3;
  (* src = "referee_1_est.v:6" *)
  output pop_0;
  (* src = "referee_1_est.v:6" *)
  output pop_1;
  (* src = "referee_1_est.v:6" *)
  output pop_2;
  (* src = "referee_1_est.v:6" *)
  output pop_3;
  (* src = "referee_1_est.v:5" *)
  output push_0;
  (* src = "referee_1_est.v:5" *)
  output push_1;
  (* src = "referee_1_est.v:5" *)
  output push_2;
  (* src = "referee_1_est.v:5" *)
  output push_3;
  (* src = "referee_1_est.v:15" *)
  wire [1:0] push_toggle;
  (* src = "referee_1_est.v:11" *)
  input reset;
  (* src = "referee_1_est.v:14" *)
  wire [3:0] wrr_pop_toggle;
  NOT _171_ (
    .A(push_toggle[0]),
    .Y(_111_)
  );
  NOT _172_ (
    .A(wrr_pop_toggle[1]),
    .Y(_112_)
  );
  NOT _173_ (
    .A(wrr_pop_toggle[2]),
    .Y(_113_)
  );
  NOT _174_ (
    .A(push_toggle[1]),
    .Y(_114_)
  );
  NOT _175_ (
    .A(reset),
    .Y(_115_)
  );
  NOT _176_ (
    .A(wrr_pop_toggle[0]),
    .Y(_116_)
  );
  NOT _177_ (
    .A(wrr_pop_toggle[3]),
    .Y(_117_)
  );
  NOT _178_ (
    .A(pop_3),
    .Y(_118_)
  );
  NOT _179_ (
    .A(pop_2),
    .Y(_119_)
  );
  NOT _180_ (
    .A(empty_1),
    .Y(_120_)
  );
  NOT _181_ (
    .A(pop_0),
    .Y(_121_)
  );
  NOT _182_ (
    .A(empty_0),
    .Y(_122_)
  );
  NOT _183_ (
    .A(push_3),
    .Y(_123_)
  );
  NOT _184_ (
    .A(push_2),
    .Y(_124_)
  );
  NOT _185_ (
    .A(push_1),
    .Y(_125_)
  );
  NOR _186_ (
    .A(almost_full_0),
    .B(almost_full_1),
    .Y(_126_)
  );
  NOR _187_ (
    .A(almost_full_2),
    .B(almost_full_3),
    .Y(_127_)
  );
  NAND _188_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  NOT _189_ (
    .A(_128_),
    .Y(_129_)
  );
  NAND _190_ (
    .A(push_toggle[0]),
    .B(_129_),
    .Y(_130_)
  );
  NOT _191_ (
    .A(_130_),
    .Y(_131_)
  );
  NAND _192_ (
    .A(_111_),
    .B(_128_),
    .Y(_132_)
  );
  NAND _193_ (
    .A(reset),
    .B(_132_),
    .Y(_133_)
  );
  NOR _194_ (
    .A(_131_),
    .B(_133_),
    .Y(_008_[0])
  );
  NOR _195_ (
    .A(_114_),
    .B(_130_),
    .Y(_134_)
  );
  NAND _196_ (
    .A(_114_),
    .B(_130_),
    .Y(_135_)
  );
  NAND _197_ (
    .A(reset),
    .B(_135_),
    .Y(_136_)
  );
  NOR _198_ (
    .A(_134_),
    .B(_136_),
    .Y(_008_[1])
  );
  NOR _199_ (
    .A(wrr_pop_toggle[2]),
    .B(wrr_pop_toggle[3]),
    .Y(_137_)
  );
  NAND _200_ (
    .A(_113_),
    .B(_117_),
    .Y(_138_)
  );
  NOR _201_ (
    .A(wrr_pop_toggle[1]),
    .B(wrr_pop_toggle[2]),
    .Y(_139_)
  );
  NAND _202_ (
    .A(_112_),
    .B(_113_),
    .Y(_140_)
  );
  NOR _203_ (
    .A(wrr_pop_toggle[0]),
    .B(_140_),
    .Y(_141_)
  );
  NAND _204_ (
    .A(_116_),
    .B(_139_),
    .Y(_142_)
  );
  NOR _205_ (
    .A(_117_),
    .B(_141_),
    .Y(_143_)
  );
  NAND _206_ (
    .A(wrr_pop_toggle[3]),
    .B(_142_),
    .Y(_144_)
  );
  NOR _207_ (
    .A(_112_),
    .B(_116_),
    .Y(_145_)
  );
  NAND _208_ (
    .A(wrr_pop_toggle[1]),
    .B(wrr_pop_toggle[0]),
    .Y(_146_)
  );
  NOR _209_ (
    .A(wrr_pop_toggle[3]),
    .B(_145_),
    .Y(_147_)
  );
  NAND _210_ (
    .A(_117_),
    .B(_146_),
    .Y(_148_)
  );
  NOR _211_ (
    .A(_137_),
    .B(_147_),
    .Y(_149_)
  );
  NAND _212_ (
    .A(_138_),
    .B(_148_),
    .Y(_150_)
  );
  NOR _213_ (
    .A(_143_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _214_ (
    .A(_144_),
    .B(_149_),
    .Y(_152_)
  );
  NOR _215_ (
    .A(empty_2),
    .B(_152_),
    .Y(_153_)
  );
  NOT _216_ (
    .A(_153_),
    .Y(_154_)
  );
  NOR _217_ (
    .A(_119_),
    .B(_152_),
    .Y(_155_)
  );
  NAND _218_ (
    .A(pop_2),
    .B(_153_),
    .Y(_156_)
  );
  NAND _219_ (
    .A(pop_1),
    .B(_120_),
    .Y(_157_)
  );
  NAND _220_ (
    .A(empty_3),
    .B(_128_),
    .Y(_158_)
  );
  NAND _221_ (
    .A(wrr_pop_toggle[0]),
    .B(_139_),
    .Y(_159_)
  );
  NOR _222_ (
    .A(_117_),
    .B(_159_),
    .Y(_160_)
  );
  NAND _223_ (
    .A(_158_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _224_ (
    .A(pop_3),
    .B(_160_),
    .Y(_162_)
  );
  NOR _225_ (
    .A(_118_),
    .B(_161_),
    .Y(_163_)
  );
  NAND _226_ (
    .A(wrr_pop_toggle[0]),
    .B(_140_),
    .Y(_164_)
  );
  NAND _227_ (
    .A(_143_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _228_ (
    .A(_163_),
    .B(_165_),
    .Y(_166_)
  );
  NOR _229_ (
    .A(pop_1),
    .B(empty_1),
    .Y(_167_)
  );
  NOR _230_ (
    .A(wrr_pop_toggle[0]),
    .B(_157_),
    .Y(_168_)
  );
  NAND _231_ (
    .A(wrr_pop_toggle[0]),
    .B(_167_),
    .Y(_169_)
  );
  NOT _232_ (
    .A(_169_),
    .Y(_170_)
  );
  NOR _233_ (
    .A(_168_),
    .B(_170_),
    .Y(_010_)
  );
  NOR _234_ (
    .A(_149_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _235_ (
    .A(wrr_pop_toggle[0]),
    .B(pop_2),
    .Y(_012_)
  );
  NOR _236_ (
    .A(wrr_pop_toggle[0]),
    .B(pop_2),
    .Y(_013_)
  );
  NOR _237_ (
    .A(empty_2),
    .B(_013_),
    .Y(_014_)
  );
  NAND _238_ (
    .A(_012_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _239_ (
    .A(_152_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _240_ (
    .A(_011_),
    .B(_016_),
    .Y(_017_)
  );
  NOT _241_ (
    .A(_017_),
    .Y(_018_)
  );
  NOR _242_ (
    .A(_166_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _243_ (
    .A(_137_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _244_ (
    .A(_116_),
    .B(pop_0),
    .Y(_021_)
  );
  NOT _245_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _246_ (
    .A(wrr_pop_toggle[0]),
    .B(_121_),
    .Y(_023_)
  );
  NOR _247_ (
    .A(_021_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _248_ (
    .A(_122_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _249_ (
    .A(_137_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _250_ (
    .A(_115_),
    .B(_137_),
    .Y(_027_)
  );
  NAND _251_ (
    .A(reset),
    .B(_138_),
    .Y(_028_)
  );
  NAND _252_ (
    .A(reset),
    .B(_026_),
    .Y(_029_)
  );
  NOR _253_ (
    .A(_020_),
    .B(_029_),
    .Y(_009_[0])
  );
  NAND _254_ (
    .A(wrr_pop_toggle[2]),
    .B(_147_),
    .Y(_030_)
  );
  NAND _255_ (
    .A(wrr_pop_toggle[1]),
    .B(_152_),
    .Y(_031_)
  );
  NOR _256_ (
    .A(wrr_pop_toggle[1]),
    .B(wrr_pop_toggle[0]),
    .Y(_032_)
  );
  NOT _257_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _258_ (
    .A(_146_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _259_ (
    .A(pop_2),
    .B(_034_),
    .Y(_035_)
  );
  NOT _260_ (
    .A(_035_),
    .Y(_036_)
  );
  NAND _261_ (
    .A(wrr_pop_toggle[1]),
    .B(pop_2),
    .Y(_037_)
  );
  NOT _262_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _263_ (
    .A(_035_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _264_ (
    .A(_036_),
    .B(_037_),
    .Y(_040_)
  );
  NOR _265_ (
    .A(_154_),
    .B(_039_),
    .Y(_041_)
  );
  NAND _266_ (
    .A(_153_),
    .B(_040_),
    .Y(_042_)
  );
  NAND _267_ (
    .A(_031_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _268_ (
    .A(_030_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _269_ (
    .A(_167_),
    .B(_034_),
    .Y(_045_)
  );
  NOR _270_ (
    .A(wrr_pop_toggle[1]),
    .B(_157_),
    .Y(_046_)
  );
  NOR _271_ (
    .A(_030_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _272_ (
    .A(_045_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _273_ (
    .A(_044_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _274_ (
    .A(_027_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _275_ (
    .A(wrr_pop_toggle[1]),
    .B(_022_),
    .Y(_051_)
  );
  NAND _276_ (
    .A(_112_),
    .B(_021_),
    .Y(_052_)
  );
  NAND _277_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _278_ (
    .A(empty_0),
    .B(_138_),
    .Y(_054_)
  );
  NAND _279_ (
    .A(reset),
    .B(_054_),
    .Y(_055_)
  );
  NOT _280_ (
    .A(_055_),
    .Y(_056_)
  );
  NAND _281_ (
    .A(_053_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _282_ (
    .A(_050_),
    .B(_057_),
    .Y(_009_[1])
  );
  NOR _283_ (
    .A(_113_),
    .B(_151_),
    .Y(_058_)
  );
  NOR _284_ (
    .A(empty_0),
    .B(_145_),
    .Y(_059_)
  );
  NAND _285_ (
    .A(pop_0),
    .B(_122_),
    .Y(_060_)
  );
  NAND _286_ (
    .A(_137_),
    .B(_060_),
    .Y(_061_)
  );
  NOT _287_ (
    .A(_061_),
    .Y(_062_)
  );
  NOR _288_ (
    .A(_059_),
    .B(_061_),
    .Y(_063_)
  );
  NOR _289_ (
    .A(_058_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _290_ (
    .A(_042_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _291_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  NOT _292_ (
    .A(_066_),
    .Y(_009_[2])
  );
  NAND _293_ (
    .A(wrr_pop_toggle[3]),
    .B(_159_),
    .Y(_067_)
  );
  NOR _294_ (
    .A(_151_),
    .B(_163_),
    .Y(_068_)
  );
  NAND _295_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _296_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NOR _297_ (
    .A(_041_),
    .B(_070_),
    .Y(_009_[3])
  );
  NAND _298_ (
    .A(reset),
    .B(_129_),
    .Y(_071_)
  );
  NOR _299_ (
    .A(_111_),
    .B(_114_),
    .Y(_072_)
  );
  NOR _300_ (
    .A(push_toggle[0]),
    .B(push_toggle[1]),
    .Y(_073_)
  );
  NOR _301_ (
    .A(_123_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _302_ (
    .A(_072_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _303_ (
    .A(_071_),
    .B(_075_),
    .Y(_007_)
  );
  NOR _304_ (
    .A(push_toggle[0]),
    .B(_114_),
    .Y(_076_)
  );
  NOR _305_ (
    .A(push_toggle[1]),
    .B(_124_),
    .Y(_077_)
  );
  NOR _306_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _307_ (
    .A(_071_),
    .B(_078_),
    .Y(_006_)
  );
  NOR _308_ (
    .A(_111_),
    .B(push_toggle[1]),
    .Y(_079_)
  );
  NOR _309_ (
    .A(_125_),
    .B(_076_),
    .Y(_080_)
  );
  NOR _310_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _311_ (
    .A(_071_),
    .B(_081_),
    .Y(_005_)
  );
  NAND _312_ (
    .A(pop_1),
    .B(_062_),
    .Y(_082_)
  );
  NAND _313_ (
    .A(pop_1),
    .B(_068_),
    .Y(_083_)
  );
  NAND _314_ (
    .A(_030_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _315_ (
    .A(_138_),
    .B(_167_),
    .Y(_085_)
  );
  NAND _316_ (
    .A(_150_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _317_ (
    .A(_084_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _318_ (
    .A(_082_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _319_ (
    .A(reset),
    .B(_088_),
    .Y(_089_)
  );
  NOT _320_ (
    .A(_089_),
    .Y(_001_)
  );
  NAND _321_ (
    .A(_149_),
    .B(_156_),
    .Y(_090_)
  );
  NOR _322_ (
    .A(_163_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _323_ (
    .A(_121_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _324_ (
    .A(pop_0),
    .B(_054_),
    .Y(_093_)
  );
  NOT _325_ (
    .A(_093_),
    .Y(_094_)
  );
  NAND _326_ (
    .A(reset),
    .B(_094_),
    .Y(_095_)
  );
  NOR _327_ (
    .A(_092_),
    .B(_095_),
    .Y(_000_)
  );
  NAND _328_ (
    .A(push_toggle[1]),
    .B(push_0),
    .Y(_096_)
  );
  NOT _329_ (
    .A(_096_),
    .Y(_097_)
  );
  NOR _330_ (
    .A(_073_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _331_ (
    .A(_071_),
    .B(_098_),
    .Y(_004_)
  );
  NAND _332_ (
    .A(_156_),
    .B(_162_),
    .Y(_099_)
  );
  NAND _333_ (
    .A(_118_),
    .B(_161_),
    .Y(_100_)
  );
  NOR _334_ (
    .A(_157_),
    .B(_030_),
    .Y(_101_)
  );
  NOR _335_ (
    .A(_028_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _336_ (
    .A(_100_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _337_ (
    .A(_099_),
    .B(_103_),
    .Y(_003_)
  );
  NOR _338_ (
    .A(_119_),
    .B(_061_),
    .Y(_104_)
  );
  NOR _339_ (
    .A(_155_),
    .B(_160_),
    .Y(_105_)
  );
  NOR _340_ (
    .A(pop_2),
    .B(_153_),
    .Y(_106_)
  );
  NOR _341_ (
    .A(_137_),
    .B(_106_),
    .Y(_107_)
  );
  NAND _342_ (
    .A(_105_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _343_ (
    .A(_101_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _344_ (
    .A(_104_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _345_ (
    .A(_115_),
    .B(_110_),
    .Y(_002_)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _346_ (
    .C(clk),
    .D(_002_),
    .Q(pop_2)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _347_ (
    .C(clk),
    .D(_003_),
    .Q(pop_3)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _348_ (
    .C(clk),
    .D(_004_),
    .Q(push_0)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _349_ (
    .C(clk),
    .D(_000_),
    .Q(pop_0)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _350_ (
    .C(clk),
    .D(_001_),
    .Q(pop_1)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _351_ (
    .C(clk),
    .D(_005_),
    .Q(push_1)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _352_ (
    .C(clk),
    .D(_006_),
    .Q(push_2)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _353_ (
    .C(clk),
    .D(_007_),
    .Q(push_3)
  );
  (* src = "referee_1_est.v:17" *)
  DFF _354_ (
    .C(clk),
    .D(_009_[0]),
    .Q(wrr_pop_toggle[0])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _355_ (
    .C(clk),
    .D(_009_[1]),
    .Q(wrr_pop_toggle[1])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _356_ (
    .C(clk),
    .D(_009_[2]),
    .Q(wrr_pop_toggle[2])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _357_ (
    .C(clk),
    .D(_009_[3]),
    .Q(wrr_pop_toggle[3])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _358_ (
    .C(clk),
    .D(_008_[0]),
    .Q(push_toggle[0])
  );
  (* src = "referee_1_est.v:17" *)
  DFF _359_ (
    .C(clk),
    .D(_008_[1]),
    .Q(push_toggle[1])
  );
endmodule
